# This script contains core ML functions for the amR pipeline.

# Declare global variables to avoid R CMD check NOTEs for tidyverse columns
utils::globalVariables(c(
  ".estimate", ".pred_Resistant", ".pred_Susceptible", ".pred_class",
  "Importance", "Sign", "Variable", "across", "adj_p_value", "antibiotic",
  "bal_acc", "coefficient", "cum_imp", "drug_or_class", "everything",
  "feature", "feature_id", "fit_mixture", "fit_trees", "gene",
  "genome_drug.genome_id", "genome_drug.resistant_phenotype", "genome_id",
  "idx_sparse", "idx_strat", "model", "n", "nmcc", "num_obs", "p_value",
  "parts", "precision", "prefix", "prop", "recall", "res_prop",
  "resistant_classes", "run_time_sec", "sig_after_bh", "stratification",
  "train_prop", "value", "where", "xlab_default_eval", "ylab_default_eval"
))

#' @importFrom dplyr all_of
#' @importFrom dplyr arrange
#' @importFrom dplyr count
#' @importFrom dplyr desc
#' @importFrom dplyr filter
#' @importFrom dplyr if_any
#' @importFrom dplyr matches
#' @importFrom dplyr mutate
#' @importFrom dplyr pull
#' @importFrom dplyr select
#' @importFrom dplyr slice
#' @importFrom hardhat tune
#' @importFrom parsnip augment
#' @importFrom parsnip boost_tree
#' @importFrom parsnip extract_fit_engine
#' @importFrom parsnip fit
#' @importFrom parsnip logistic_reg
#' @importFrom parsnip multinom_reg
#' @importFrom parsnip rand_forest
#' @importFrom parsnip set_engine
#' @importFrom parsnip set_mode
#' @importFrom purrr imap_dfr
#' @importFrom recipes all_predictors
#' @importFrom recipes recipe
#' @importFrom recipes step_normalize
#' @importFrom recipes step_pca
#' @importFrom recipes step_zv
#' @importFrom recipes update_role
#' @importFrom rlang eval_tidy
#' @importFrom rsample initial_split
#' @importFrom rsample initial_validation_split
#' @importFrom rsample training
#' @importFrom rsample validation_set
#' @importFrom rsample vfold_cv
#' @importFrom stats coef
#' @importFrom tibble tibble
#' @importFrom tidyr pivot_wider
#' @importFrom tune control_grid
#' @importFrom tune finalize_workflow
#' @importFrom tune select_best
#' @importFrom tune tune_grid
#' @importFrom vip vi
#' @importFrom workflows add_model
#' @importFrom workflows add_recipe
#' @importFrom workflows workflow
#' @importFrom workflowsets extract_fit_parsnip
#' @importFrom workflowsets extract_spec_parsnip
#' @importFrom yardstick bal_accuracy
#' @importFrom yardstick conf_mat
#' @importFrom yardstick f_meas
#' @importFrom yardstick mcc
#' @importFrom yardstick metric_set
#' @importFrom yardstick pr_auc
NULL

#' splitMLInputTibble()
#'
#' Splits an ML-ready tibble into training and testing (and in some cases
#' validation) sets.
#'
#' @param ml_input_tibble An ML-ready tibble generated by `loadMLInputTibble()`.
#' This must have a target variable column named either
#' `genome_drug.resistant_phenotype` ("Resistant" or "Susceptible "
#' classification for one bug/drug combination) or `resistant_classes`
#' (multi-class classification for determining the drug classes to which each
#' genome is resistant), but not both.
#' @param split [num] Vector of length 2 indicating the proportion of data to
#' be designated as training and validation, respectively.
#' @param seed [num] For reproducible analysis
#' @return An `rsplit` object
#' @export
splitMLInputTibble <- function(
  ml_input_tibble, split = c(0.6, 0.2),
  seed = 123
) {
  .checkArgTibble(ml_input_tibble, ml = TRUE)
  .checkArgSplit(split)
  .checkArgSeed(seed)

  set.seed(seed)

  target_var <- getTargetVarName(ml_input_tibble)

  # Split the data, maintaining R/S proportions.
  if (split[2] == 0) {
    data_split <- rsample::initial_split(ml_input_tibble,
      prop = split[1],
      strata = !!target_var
    )
  } else {
    data_split <- rsample::initial_validation_split(ml_input_tibble,
      prop = split, strata = !!target_var
    )
  }

  return(data_split)
}

#' buildRecipe()
#'
#' Specify predictors, outcome, and metadata by building a recipe.
#'
#' @importFrom stats reformulate
#'
#' @param train_data The part of the feature data designated for ML model
#' training. This can be the output of
#' `rsample::training(splitMLInputTibble(ml_input_tibble))`.
#' @param use_pca [bool] Set to `TRUE` to use PCA instead of all features.
#' @param pca_threshold [num] The proportion of total variance for which the
#' principle components account
#' @return A `recipe` object
#' @export
buildRecipe <- function(train_data, use_pca = FALSE, pca_threshold = 0.95) {
  .checkArgTibble(train_data, ml = TRUE)
  .checkArgUsePCA(use_pca)
  .checkArgPCAThreshold(pca_threshold)

  target_var <- getTargetVarName(train_data) |> as.character()

  recipe <- recipes::recipe(
    formula = reformulate(".", response = target_var),
    data = train_data
  ) |>
    # Tell recipe to keep metadata columns but not use them as predictors or
    # outcome.
    recipes::update_role(!dplyr::all_of(target_var) & dplyr::matches("^genome"),
      new_role = "metadata"
    ) |>
    recipes::step_zv(recipes::all_predictors()) |>
    recipes::step_normalize(recipes::all_predictors())

  if (use_pca) {
    recipe <- recipe |>
      recipes::step_pca(recipes::all_predictors(), threshold = pca_threshold)
  }

  return(recipe)
}

#' buildLRModel()
#'
#' Builds a logistic regression model.
#'
#' @param multi_class [bool] Whether to construct a model for multi-class
#' classification
#' @return A `parsnip` `logistic_reg` object
#' @export
buildLRModel <- function(multi_class = FALSE) {
  .checkArgMultiClass(multi_class)

  if (!multi_class) {
    lr_mod <- parsnip::logistic_reg(
      penalty = hardhat::tune(),
      mixture = hardhat::tune()
    ) |>
      parsnip::set_engine(engine = "glmnet")
  } else if (multi_class) {
    lr_mod <- parsnip::multinom_reg(
      penalty = hardhat::tune(),
      mixture = hardhat::tune()
    ) |>
      parsnip::set_engine(engine = "glmnet")
  }

  return(lr_mod)
}

#' buildRFModel()
#'
#' Builds a random forest model.
#'
#' @return A `parsnip` `rand_forest` object
#' @export
buildRFModel <- function() {
  rf_mod <- parsnip::rand_forest(
    trees = hardhat::tune(),
    mtry = hardhat::tune(), min_n = hardhat::tune()
  ) |>
    parsnip::set_engine("ranger", importance = "impurity") |>
    parsnip::set_mode("classification")

  return(rf_mod)
}

#' buildBTModel()
#'
#' Builds a boosted tree model.
#'
#' @return A `parsnip` `boost_tree` object
#' @export
buildBTModel <- function() {
  bt_mod <- parsnip::boost_tree(
    mode = "classification",
    mtry = hardhat::tune(), trees = hardhat::tune(), min_n = hardhat::tune()
  )

  return(bt_mod)
}

#' buildWflow()
#'
#' Builds a `tidymodels` workflow based on an input model and recipe.
#'
#' @param parsnip_mod A `parsnip` model object, such as the output of
#' `buildLRModel()`, `buildRFModel()`, or `buildBTModel()`
#' @param recipe A recipe, such as the output of `buildRecipe()`
#' @return A `workflow` object
#' @export
buildWflow <- function(parsnip_mod, recipe) {
  .checkArgParsnipMod(parsnip_mod)
  .checkArgRecipe(recipe)

  wflow <- workflows::workflow() |>
    workflows::add_model(parsnip_mod) |>
    workflows::add_recipe(recipe)

  return(wflow)
}

#' buildTuningGrid()
#'
#' Builds a tuning grid according to the input model.
#'
#' @param model [chr]  Logistic regression ("LR"), random forest ("RF"), or
#' boosted tree ("BT")
#' @param penalty_vec [num] A vector containing `penalty` (regularization
#' strength) values to try (for logistic regression). It is recommended to
#' choose values in the range 10^-4 to 10^4.
#' @param mix_vec [num] A vector containing `mixture` values to try for logistic
#' regression. 0 corresponds to L2 regularization; 1 corresponds to L1;
#' intermediate values (0, 1) correspond to elastic net.
#' @param n_feat [num] Number of features in pangenome. Used to
#' calculate `mtry` values for a subsequent grid search (for random forest or
#' boosted tree). Output of `getNumFeat()`.
#' @param min_n_vec [num] A vector containing `min_n` values (the number of data
#' points in a node required for the node to be split) to try for random forest
#' or boosted tree. It is recommended to choose values \eqn{[1, 100]}.
#' @param tree_vec [num] A vector containing values to try for the number of
#' `trees` in random forest or boosted tree. It is recommended to choose values
#' in the range 100 to 1000.
#' @return A logistic regression, random forest, or boosted tree tuning grid as
#' a tibble
#' @export
buildTuningGrid <- function(
  model = "LR",
  penalty_vec = 10^seq(-4, -1, length.out = 10), mix_vec = 0:5 / 5, n_feat = NA,
  min_n_vec = c(2, 6, 12), tree_vec = c(100, 500, 1000)
) {
  .checkArgModel(model)

  if (model == "LR") {
    .checkArgPenaltyVec(penalty_vec)
    .checkArgMixVec(mix_vec)

    penalty <- rep(penalty_vec, each = length(mix_vec))
    mixture <- rep(mix_vec, length(penalty_vec))

    grid <- tibble::tibble(penalty, mixture)
  }

  if (model == "RF" || model == "BT") {
    .checkArgNFeat(n_feat)
    .checkArgMinNVec(min_n_vec)
    .checkArgTreeVec(tree_vec)

    mtry_vec <- c(sqrt(n_feat), 10 * sqrt(n_feat), 0.1 * sqrt(n_feat))
    mtry <- rep(mtry_vec, each = length(min_n_vec) * length(tree_vec))
    min_n <- rep(rep(min_n_vec, each = length(tree_vec)), length(mtry_vec))
    trees <- rep(tree_vec, length(min_n_vec) * length(mtry_vec))

    grid <- tibble::tibble(mtry, min_n, trees)
  }

  return(grid)
}

#' tuneGrid()
#'
#' Tunes the model according to the tuning grid, workflow, and data split
#' specified.
#'
#' @param wflow A `workflow` object, such as the output of `buildWflow()`
#' @param data_split An `rsplit` object, such as the output of
#' `splitMLInputTibble()`.
#' @param grid A tuning grid as a tibble, such as the output of
#' `buildTuningGrid()`
#' @param n_fold [num] Number of folds of cross-validation
#' @return Results of grid tuning
#' @export
tuneGrid <- function(
  wflow, data_split, grid = buildTuningGrid(model = "LR"),
  n_fold = 2
) {
  .checkArgTibble(grid)
  .checkArgWflow(wflow)
  .checkArgDataSplit(data_split)

  if (workflowsets::extract_spec_parsnip(wflow)$engine == "xgboost") {
    if (!requireNamespace("xgboost", quietly = TRUE)) {
      stop(paste(
        "The `xgboost` package is required for this functionality.",
        "Please install it with `install.packages('xgboost')`"
      ), call. = FALSE)
    }
  }

  target_var <- getTargetVarName(data_split[[1]]) |> as.character()

  if (class(data_split)[1] == "initial_split") {
    .checkArgNFold(n_fold)

    train_data <- data_split |> rsample::training()

    resamples <- rsample::vfold_cv(train_data, v = n_fold, strata = target_var)
  } else if (class(data_split)[1] == "initial_validation_split") {
    resamples <- rsample::validation_set(data_split)
  }

  tune_res <- tune::tune_grid(wflow,
    resamples = resamples, grid = grid,
    control = tune::control_grid(save_pred = TRUE),
    metrics = yardstick::metric_set(
      yardstick::f_meas, yardstick::pr_auc,
      yardstick::bal_accuracy, yardstick::mcc
    )
  )

  return(tune_res)
}

#' selectBestModel()
#'
#' Selects best model by F1 score, AUPRC, MCC, or balanced accuracy.
#'
#' @param tune_res Results of grid tuning, such as the output of `tuneGrid()`
#' @param wflow A `workflows` object, such as the output of `buildWflow()`
#' @param select_best_metric [chr] Metric to select best model: "f_meas",
#' "pr_auc", "mcc", or "bal_accuracy"
#' @return Best model workflow
#' @export
selectBestModel <- function(tune_res, wflow, select_best_metric = "mcc") {
  .checkArgTuneRes(tune_res)
  .checkArgWflow(wflow)
  .checkArgSelectBestMetric(select_best_metric)

  best_mod <- tune::select_best(tune_res, metric = select_best_metric)
  final_mod <- tune::finalize_workflow(wflow, best_mod)

  return(final_mod)
}

#' fitBestModel()
#'
#' Fits the best model (output of `selectBestModel()`).
#'
#' @param final_mod Best model workflow (output of `selectBestModel()`)
#' @param train_data The part of the pangenome data designated for ML model
#' training. This can be the output of
#' `rsample::training(splitMLInputTibble(ml_input_tibble))`.
#' @return Best model fit
#' @export
fitBestModel <- function(final_mod, train_data) {
  .checkArgWflow(final_mod)
  .checkArgTibble(train_data, ml = TRUE)

  fit <- final_mod |> parsnip::fit(data = train_data)

  return(fit)
}

#' getFitHps()
#'
#' Returns the hyperparameters that were used to fit the best model.
#'
#' @param fit Best model fit, such as the output of `fitBestModel()`
#' @return Hyperparameters used to fit the final model
#' @export
getFitHps <- function(fit) {
  .checkArgWflow(fit)

  model <- class(fit$fit$actions$model$spec)[1]

  if (model == "logistic_reg" || model == "multinom_reg") {
    fit_hps <- tibble::tibble(
      penalty = fit$fit$fit$spec$args$penalty,
      mixture = rlang::eval_tidy(fit$fit$fit$spec$args$mixture)
    )
  } else if (model == "rand_forest" || model == "boost_tree") {
    fit_hps <- tibble::tibble(
      mtry = rlang::eval_tidy(fit$fit$fit$spec$args$mtry),
      trees = rlang::eval_tidy(fit$fit$fit$spec$args$trees),
      min_n = rlang::eval_tidy(fit$fit$fit$spec$args$min_n)
    )
  } else {
    stop(paste(
      "The `fit` object provided must correspond to",
      "'logistic_reg', 'multinom_reg', 'rand_forest', or 'boost_tree'."
    ))
  }

  return(fit_hps)
}

#' predict()
#'
#' Predicts the AMR phenotype in the test data set based on the best fit ML
#' model.
#'
#' @param fit Best model fit, such as the output of `fitBestModel()`
#' @param test_data The part of the pangenome data designated for ML model
#' testing. This can be the output of
#' `rsample::testing(splitMLInputTibble(ml_input_tibble))`.
#' @return Test data (tibble) with an added column for predicted phenotype
#' labels
#' @export
predict <- function(fit, test_data) {
  .checkArgWflow(fit)
  .checkArgTibble(test_data, ml = TRUE)

  test_data_plus_predictions <- parsnip::augment(fit, test_data)

  return(test_data_plus_predictions)
}

#' getConfusionMatrix()
#'
#' Returns the confusion matrix based on the AMR phenotype predictions by an ML
#' model compared against the actual values.
#'
#' @param test_data_plus_predictions Test data (tibble) with an added column for
#' predicted phenotype labels, such as the output of `predict()`
#' @return Confusion matrix of class `conf_mat`
#' @export
getConfusionMatrix <- function(test_data_plus_predictions) {
  .checkArgTestDataPlusPredictions(test_data_plus_predictions)

  target_var <- getTargetVarName(test_data_plus_predictions)

  CM <- test_data_plus_predictions |>
    yardstick::conf_mat(truth = !!target_var, estimate = .pred_class)

  return(CM)
}

#' calculatenMCC()
#'
#' Returns the normalized (to a 0 to 1 scale instead of -1 to 1) Matthews
#' correlation coefficient (nMCC) based on the AMR phenotype predictions by an
#' ML model compared against the actual values.
#'
#' @inheritParams getConfusionMatrix
#' @return Normalized (to a 0 to 1 scale instead of -1 to 1) Matthews
#' correlation coefficient (nMCC)
#' @export
calculatenMCC <- function(test_data_plus_predictions) {
  .checkArgTestDataPlusPredictions(test_data_plus_predictions)

  target_var <- getTargetVarName(test_data_plus_predictions)

  mcc <- test_data_plus_predictions |>
    yardstick::mcc(truth = !!target_var, estimate = .pred_class) |>
    dplyr::select(.estimate) |>
    as.numeric()

  nmcc <- (mcc + 1) / 2

  return(round(nmcc, 2))
}

#' calculateF1()
#'
#' Returns the F1 score based on the AMR phenotype predictions by an ML model
#' compared against the actual values.
#'
#' @inheritParams getConfusionMatrix
#' @return F1 score
#' @export
calculateF1 <- function(test_data_plus_predictions) {
  .checkArgTestDataPlusPredictions(test_data_plus_predictions)

  if (!("genome_drug.resistant_phenotype" %in%
    colnames(test_data_plus_predictions))) {
    stop(paste(
      "`test_data_plus_predictions` does not have a column for",
      "`genome_drug.resistant_phenotype`."
    ))
  }

  f1 <- test_data_plus_predictions |>
    yardstick::f_meas(
      truth = genome_drug.resistant_phenotype,
      estimate = .pred_class
    ) |>
    dplyr::select(.estimate) |>
    as.numeric() |>
    round(2)

  return(f1)
}

#' calculateAUPRC()
#'
#' Returns the area under the precision-recall curve (AUPRC) based on the AMR
#' phenotype predictions by an ML model compared against the actual values.
#'
#' @inheritParams getConfusionMatrix
#' @return AUPRC
#' @export
calculateAUPRC <- function(test_data_plus_predictions) {
  .checkArgTestDataPlusPredictions(test_data_plus_predictions)

  if (!("genome_drug.resistant_phenotype" %in%
    colnames(test_data_plus_predictions))) {
    stop(paste(
      "`test_data_plus_predictions` does not have a column for",
      "`genome_drug.resistant_phenotype`."
    ))
  }

  auprc <- test_data_plus_predictions |>
    yardstick::pr_auc(
      truth = genome_drug.resistant_phenotype, .pred_Resistant
    ) |>
    dplyr::select(.estimate) |>
    as.numeric() |>
    round(2)

  return(auprc)
}

#' calculateLog2APOP()
#'
#' Returns log2(AUPRC/prior) based on the AMR phenotype predictions by an ML
#' model compared against the actual values.
#'
#' @inheritParams getConfusionMatrix
#' @return log2(AUPRC/prior)
#' @export
calculateLog2APOP <- function(test_data_plus_predictions) {
  .checkArgTestDataPlusPredictions(test_data_plus_predictions)

  if (!("genome_drug.resistant_phenotype" %in%
    colnames(test_data_plus_predictions))) {
    stop(paste(
      "`test_data_plus_predictions` does not have a column for",
      "`genome_drug.resistant_phenotype`."
    ))
  }

  auprc <- calculateAUPRC(test_data_plus_predictions)
  prior <- sum(
    test_data_plus_predictions$genome_drug.resistant_phenotype == "Resistant"
  ) /
    nrow(test_data_plus_predictions)

  if (prior > 0.3 && prior < 0.7) {
    warning(paste(
      "Classes are roughly balanced.",
      "Calculation of log2(AUPRC/prior) may be inappropriate."
    ))
  } else if (prior >= 0.7) {
    warning(paste(
      "Classes are imbalanced toward the resistant phenotype.",
      "Calculation of log2(AUPRC/prior) may be inappropriate."
    ))
  }

  log2_apop <- log2(auprc / prior) |> round(2)

  return(log2_apop)
}

#' calculateBalAcc()
#'
#' Returns the balanced accuracy based on the AMR phenotype predictions by an
#' ML model compared against the actual values.
#'
#' @inheritParams getConfusionMatrix
#' @return Balanced accuracy
#' @export
calculateBalAcc <- function(test_data_plus_predictions) {
  .checkArgTestDataPlusPredictions(test_data_plus_predictions)

  if (!("genome_drug.resistant_phenotype" %in%
    colnames(test_data_plus_predictions))) {
    stop(paste(
      "`test_data_plus_predictions` does not have a column for",
      "`genome_drug.resistant_phenotype`."
    ))
  }

  bal_acc <- test_data_plus_predictions |>
    yardstick::bal_accuracy(
      truth = genome_drug.resistant_phenotype, estimate = .pred_class
    ) |>
    dplyr::select(.estimate) |>
    as.numeric() |>
    round(2)

  return(bal_acc)
}

#' calculateSensitivity()
#'
#' Returns the sensitivity based on the AMR phenotype predictions by an ML model
#' compared against the actual values.
#'
#' @inheritParams getConfusionMatrix
#' @return sensitivity
#' @export
calculateSensitivity <- function(test_data_plus_predictions) {
  .checkArgTestDataPlusPredictions(test_data_plus_predictions)

  if (!("genome_drug.resistant_phenotype" %in%
    colnames(test_data_plus_predictions))) {
    stop(paste(
      "`test_data_plus_predictions` does not have a column for",
      "`genome_drug.resistant_phenotype`."
    ))
  }

  sens <- test_data_plus_predictions |>
    yardstick::sens(
      truth = genome_drug.resistant_phenotype,
      estimate = .pred_class
    ) |>
    dplyr::select(.estimate) |>
    as.numeric() |>
    round(2)

  return(sens)
}

#' calculateSpecificity()
#'
#' Returns the specificity score based on the AMR phenotype predictions by an ML model
#' compared against the actual values.
#'
#' @inheritParams getConfusionMatrix
#' @return specificity
#' @export
calculateSpecificity <- function(test_data_plus_predictions) {
  .checkArgTestDataPlusPredictions(test_data_plus_predictions)

  if (!("genome_drug.resistant_phenotype" %in%
    colnames(test_data_plus_predictions))) {
    stop(paste(
      "`test_data_plus_predictions` does not have a column for",
      "`genome_drug.resistant_phenotype`."
    ))
  }

  spec <- test_data_plus_predictions |>
    yardstick::spec(
      truth = genome_drug.resistant_phenotype,
      estimate = .pred_class
    ) |>
    dplyr::select(.estimate) |>
    as.numeric() |>
    round(2)

  return(spec)
}

#' calculateEvalMets()
#'
#' Returns the F1 score, area under the precision-recall curve (AUPRC), balanced
#' accuracy, normalized (to a 0 to 1 scale instead of -1 to 1) Matthews
#' correlation coefficient (nMCC), and log2(AUPRC/prior) based on the AMR
#' phenotype predictions by an ML model compared against the actual values.
#'
#' @inheritParams getConfusionMatrix
#' @return F1 score, AUPRC, balanced accuracy, nMCC, and log2(AUPRC/prior)
#' @export
calculateEvalMets <- function(test_data_plus_predictions) {
  .checkArgTestDataPlusPredictions(test_data_plus_predictions)

  f1 <- calculateF1(test_data_plus_predictions)
  auprc <- calculateAUPRC(test_data_plus_predictions)
  bal_acc <- calculateBalAcc(test_data_plus_predictions)
  sens <- calculateSensitivity(test_data_plus_predictions)
  spec <- calculateSpecificity(test_data_plus_predictions)
  nmcc <- calculatenMCC(test_data_plus_predictions)
  log2_apop <- calculateLog2APOP(test_data_plus_predictions)

  return(c(f1, auprc, bal_acc, nmcc, log2_apop))
}

#' extractTopFeats()
#'
#' Returns the top features that an ML model found to be important for
#' predicting the AMR phenotype of a given pathogen.
#'
#' @param fit Best model fit, such as the output of `fitBestModel()`
#' @param prop_vi_top_feats [num] A vector of length 2 with elements together
#' indicating the proportion of total variable importance the top features
#' should comprise. To get the features that contribute to the top 10 to 20% of
#' total variable importance, for example, set
#' `prop_vi_top_feats = c(0.1, 0.2)`.
#' Returns all features by default.
#' @param n_top_feats [num] Number of top features to extract
#' @return A tibble with a column for top features (`Variable`), a column for
#' `Importance`, and a column for `Sign` (or, for multi-class, a tibble with
#' per-class columns of importance scores for each `Variable`)
#' @export
extractTopFeats <- function(
  fit, prop_vi_top_feats = c(0, 1),
  n_top_feats = NA
) {
  .checkArgWflow(fit)

  if (!is.na(n_top_feats)) {
    prop_vi_top_feats <- NA
  }

  # Arg checking for every permutation of `prop_vi_top_feats` and `n_top_feats`
  if (is.na(n_top_feats) & any(!is.na(prop_vi_top_feats))) {
    .checkArgPropVITopFeats(prop_vi_top_feats)
  } else if (any(is.na(prop_vi_top_feats)) & !is.na(n_top_feats)) {
    .checkArgNTopFeats(n_top_feats)
  } else if (any(!is.na(prop_vi_top_feats)) & !is.na(n_top_feats)) {
    stop("Set either `n_top_feats` or `prop_vi_top_feats` to `NA` but not
      both.")
  } else if (any(is.na(prop_vi_top_feats)) & is.na(n_top_feats)) {
    stop("Please specify either `n_top_feats` or `prop_vi_top_feats`.")
  }

  feats_arranged <- fit |>
    workflowsets::extract_fit_parsnip() |>
    vip::vi() |>
    dplyr::arrange(dplyr::desc(Importance))

  if (!is.na(n_top_feats)) {
    top_feats_and_VIs <- feats_arranged |> dplyr::slice(1:n_top_feats)
  } else if (any(!is.na(prop_vi_top_feats))) {
    cum_vi_lower <- prop_vi_top_feats[1] * sum(feats_arranged$Importance)
    cum_vi_upper <- prop_vi_top_feats[2] * sum(feats_arranged$Importance)

    top_feats_and_VIs <- feats_arranged |>
      dplyr::mutate(cum_imp = cumsum(Importance)) |>
      dplyr::filter(cum_imp < cum_vi_upper & cum_imp > cum_vi_lower)
  }

  top_feat_tibble <- tibble::tibble(
    Variable = dplyr::pull(top_feats_and_VIs, Variable),
    Importance = dplyr::pull(top_feats_and_VIs, Importance),
    Sign = dplyr::pull(top_feats_and_VIs, Sign)
  )

  # Take a different approach if using multi-class (the previous code would give
  # a less meaningful result).
  if (class(fit$fit$actions$model$spec)[1] == "multinom_reg") {
    warning(paste(
      "Extracting top features from a multi-class model.",
      "The `prop_vi_top_feats` and `n_top_feats` arguments do not apply."
    ))

    fit_penalty <- getFitHps(fit)["penalty"] |> as.numeric()
    glmnet_fit <- parsnip::extract_fit_engine(fit)
    coefs <- stats::coef(glmnet_fit, s = fit_penalty)

    importance_table <- purrr::imap_dfr(coefs, function(mat, class) {
      mat_dense <- as.matrix(mat)
      tibble::tibble(
        class = class,
        Variable = rownames(mat_dense)[-1], # Exclude intercept.
        coefficient = mat_dense[-1, 1] # Get coefficients as numeric vector.
      )
    })

    top_feat_tibble <- importance_table |>
      dplyr::select(Variable, class, coefficient) |>
      tidyr::pivot_wider(
        names_from = class,
        values_from = coefficient,
        values_fill = 0 # Fill missing values with 0.
      ) |>
      dplyr::filter(dplyr::if_any(-Variable, ~ . != 0))
  }

  return(top_feat_tibble)
}
