# This script contains core ML functions for the amR pipeline.

#' @importFrom dplyr all_of
#' @importFrom dplyr arrange
#' @importFrom dplyr count
#' @importFrom dplyr desc
#' @importFrom dplyr filter
#' @importFrom dplyr if_any
#' @importFrom dplyr matches
#' @importFrom dplyr mutate
#' @importFrom dplyr pull
#' @importFrom dplyr select
#' @importFrom dplyr slice
#' @importFrom hardhat tune
#' @importFrom methods is
#' @importFrom parsnip augment
#' @importFrom parsnip boost_tree
#' @importFrom parsnip extract_fit_engine
#' @importFrom parsnip fit
#' @importFrom parsnip logistic_reg
#' @importFrom parsnip multinom_reg
#' @importFrom parsnip rand_forest
#' @importFrom parsnip set_engine
#' @importFrom parsnip set_mode
#' @importFrom purrr imap_dfr
#' @importFrom recipes all_predictors
#' @importFrom recipes recipe
#' @importFrom recipes step_normalize
#' @importFrom recipes step_pca
#' @importFrom recipes step_zv
#' @importFrom recipes update_role
#' @importFrom rlang eval_tidy
#' @importFrom rsample initial_split
#' @importFrom rsample initial_validation_split
#' @importFrom rsample training
#' @importFrom rsample validation_set
#' @importFrom rsample vfold_cv
#' @importFrom stats coef
#' @importFrom stats reformulate
#' @importFrom tibble tibble
#' @importFrom tidyr pivot_wider
#' @importFrom tune control_grid
#' @importFrom tune finalize_workflow
#' @importFrom tune select_best
#' @importFrom tune tune_grid
#' @importFrom vip vi
#' @importFrom workflows add_model
#' @importFrom workflows add_recipe
#' @importFrom workflows workflow
#' @importFrom workflowsets extract_fit_parsnip
#' @importFrom workflowsets extract_spec_parsnip
#' @importFrom yardstick bal_accuracy
#' @importFrom yardstick conf_mat
#' @importFrom yardstick f_meas
#' @importFrom yardstick mcc
#' @importFrom yardstick metric_set
#' @importFrom yardstick pr_auc
NULL

#' splitMLInputTibble()
#'
#' Splits an ML-ready tibble into training and testing (and in some cases
#' validation) sets.
#'
#' @param ml_input_tibble An ML-ready tibble generated by `loadMLInputTibble()`.
#' This must have a target variable column named either
#' `genome_drug.resistant_phenotype` ("Resistant" or "Susceptible "
#' classification for one bug/drug combination) or `resistant_classes`
#' (multi-class classification for determining the drug classes to which each
#' genome is resistant), but not both.
#' @param split [num] Vector of length 2 indicating the proportion of data to
#' be designated as training and validation, respectively.
#' @param seed [num] Optional. If supplied, the split is seeded (and the
#' caller's RNG state restored afterward) for standalone reproducibility. When
#' `NULL` (the default, as used by `runMLPipeline()`), the split inherits the
#' ambient RNG stream so it can share one seed with downstream tuning and fitting.
#' @return An `rsplit` object
#' @examples
#' ml <- tibble::tibble(
#'   genome_id = paste0("g", 1:20),
#'   genome_drug.resistant_phenotype = rep(c("Resistant", "Susceptible"), each = 10),
#'   feat_a = rep(c(0L, 1L), 10),
#'   feat_b = rep(c(1L, 0L), 10)
#' )
#' splitMLInputTibble(ml, split = c(1, 0), seed = 42)
#' @export
splitMLInputTibble <- function(ml_input_tibble, split = c(0.6, 0.2), seed = NULL) {
  .checkArgTibble(ml_input_tibble, ml = TRUE)
  .checkArgSplit(split)
  if (!is.null(seed)) {
    .checkArgSeed(seed)
    withr::local_seed(seed)
  }

  target_var <- .getTargetVarName(ml_input_tibble)

  # Split the data, maintaining R/S proportions.
  if (split[2] == 0) {
    # CV mode: retain a stratified testing holdout purely for final reporting
    # metrics; CV is only performed on the training portion.
    prop_train_for_holdout <- 0.8 # 80 percent train, 20 percent reserved test
    data_split <- rsample::initial_split(
      ml_input_tibble,
      prop   = prop_train_for_holdout,
      strata = !!target_var
    )
  } else {
    data_split <- rsample::initial_validation_split(
      ml_input_tibble,
      prop   = split,
      strata = !!target_var
    )
  }
  return(data_split)
}

#' buildRecipe()
#'
#' Specify predictors, outcome, and metadata by building a recipe.
#'
#' @param train_data The part of the feature data designated for ML model
#' training. This can be the output of
#' `rsample::training(splitMLInputTibble(ml_input_tibble))`.
#' @param use_pca [bool] Set to `TRUE` to use PCA instead of all features.
#' @param pca_threshold [num] The proportion of total variance for which the
#' principle components account
#' @return A `recipe` object
#' @examples
#' train <- tibble::tibble(
#'   genome_id = paste0("g", 1:10),
#'   genome_drug.resistant_phenotype = rep(c("Resistant", "Susceptible"), each = 5),
#'   feat_a = rep(c(0L, 1L), 5),
#'   feat_b = rep(c(1L, 0L), 5)
#' )
#' buildRecipe(train, use_pca = FALSE)
#' @export
buildRecipe <- function(train_data, use_pca = FALSE, pca_threshold = 0.95) {
  .checkArgTibble(train_data, ml = TRUE)
  .checkArgUsePCA(use_pca)
  .checkArgPCAThreshold(pca_threshold)

  target_var <- .getTargetVarName(train_data) |> as.character()

  # Pick only true metadata/ID columns that start with "genome"
  nm <- names(train_data)
  id_cols <- setdiff(nm[grepl("^genome", nm)], target_var)

  rec <- recipes::recipe(
    formula = stats::reformulate(".", response = target_var),
    data = train_data
  )

  # Only update roles if we actually have ID columns to mark as metadata
  if (length(id_cols) > 0) {
    rec <- rec |>
      recipes::update_role(dplyr::all_of(id_cols), new_role = "metadata")
  }

  rec <- rec |>
    recipes::step_zv(recipes::all_predictors()) |>
    recipes::step_normalize(recipes::all_predictors())

  if (isTRUE(use_pca)) {
    rec <- rec |>
      recipes::step_pca(recipes::all_predictors(), threshold = pca_threshold)
  }

  rec
}


#' buildLRModel()
#'
#' Builds a logistic regression model.
#'
#' @param multi_class [bool] Whether to construct a model for multi-class
#' classification
#' @return A `parsnip` `logistic_reg` object
#' @examples
#' buildLRModel()
#' buildLRModel(multi_class = TRUE)
#' @export
buildLRModel <- function(multi_class = FALSE) {
  .checkArgMultiClass(multi_class)

  if (!multi_class) {
    lr_mod <- parsnip::logistic_reg(
      penalty = hardhat::tune(),
      mixture = hardhat::tune()
    ) |>
      parsnip::set_engine(engine = "glmnet")
  } else if (multi_class) {
    lr_mod <- parsnip::multinom_reg(
      penalty = hardhat::tune(),
      mixture = hardhat::tune()
    ) |>
      parsnip::set_engine(engine = "glmnet")
  }

  return(lr_mod)
}

#' buildWflow()
#'
#' Builds a `tidymodels` workflow based on an input model and recipe.
#'
#' @param parsnip_mod A `parsnip` model object, such as the output of
#' `buildLRModel()` (random forest and boosted tree support planned)
#' @param recipe A recipe, such as the output of `buildRecipe()`
#' @return A `workflow` object
#' @examples
#' train <- tibble::tibble(
#'   genome_id = paste0("g", 1:10),
#'   genome_drug.resistant_phenotype = rep(c("Resistant", "Susceptible"), each = 5),
#'   feat_a = rep(c(0L, 1L), 5),
#'   feat_b = rep(c(1L, 0L), 5)
#' )
#' rec <- buildRecipe(train, use_pca = FALSE)
#' lr <- buildLRModel()
#' buildWflow(lr, rec)
#' @export
buildWflow <- function(parsnip_mod, recipe) {
  .checkArgParsnipMod(parsnip_mod)
  .checkArgRecipe(recipe)

  wflow <- workflows::workflow() |>
    workflows::add_model(parsnip_mod) |>
    workflows::add_recipe(recipe)

  return(wflow)
}

#' buildTuningGrid()
#'
#' Builds a tuning grid according to the input model.
#'
#' @param model [chr]  Currently, logistic regression ("LR") is supported.
#' @param penalty_vec [num] A vector containing `penalty` (regularization
#' strength) values to try (for logistic regression). Recommended range:
#' 10^-4 to 10^4.
#' @param mix_vec [num] A vector containing `mixture` values to try for logistic
#' regression. 0 corresponds to L2 regularization; 1 corresponds to L1;
#' intermediate values (0, 1) correspond to elastic net.
#' @return A logistic regression tuning grid as a tibble
#' @examples
#' buildTuningGrid(
#'   model       = "LR",
#'   penalty_vec = 10^c(-3, -1),
#'   mix_vec     = c(0, 0.5, 1)
#' )
#' @export
buildTuningGrid <- function(
  model = "LR",
  penalty_vec = 10^seq(-4, -1, length.out = 10),
  mix_vec = 0:5 / 5
) {
  .checkArgModel(model)

  if (model == "LR") {
    .checkArgPenaltyVec(penalty_vec)
    .checkArgMixVec(mix_vec)

    penalty <- rep(penalty_vec, each = length(mix_vec))
    mixture <- rep(mix_vec, length(penalty_vec))
    grid <- tibble::tibble(penalty, mixture)
  }

  return(grid)
}


#' tuneGrid()
#'
#' Tunes the model according to the tuning grid, workflow, and data split
#' specified.
#'
#' @param wflow A `workflow` object, such as the output of `buildWflow()`
#' @param data_split An `rsplit` object, such as the output of
#' `splitMLInputTibble()`.
#' @param grid A tuning grid as a tibble, such as the output of
#' `buildTuningGrid()`
#' @param n_fold [num] Number of folds of cross-validation
#' @return Results of grid tuning
#' @examples
#' data(demo_ml_tibble)
#' data_split <- splitMLInputTibble(demo_ml_tibble, split = c(1, 0), seed = 1)
#' wflow <- buildWflow(
#'   buildLRModel(),
#'   buildRecipe(rsample::training(data_split))
#' )
#' grid <- buildTuningGrid("LR", 10^c(-3, -1), c(0, 0.5, 1))
#' set.seed(1)
#' tuneGrid(wflow, data_split, grid, n_fold = 2)
#' @export
tuneGrid <- function(wflow, data_split, grid = buildTuningGrid(model = "LR"),
                     n_fold = 5) {
  .checkArgTibble(grid)
  .checkArgWflow(wflow)
  .checkArgDataSplit(data_split)

  # Always do CV on the training portion of the split
  train_df <- rsample::training(data_split)
  target_var <- .getTargetVarName(train_df)

  if (is(data_split, "initial_split")) {
    # CV on training portion; final eval will use the held-out test set
    resamples <- rsample::vfold_cv(train_df, v = n_fold, strata = !!target_var)
  } else if (is(data_split, "initial_validation_split")) {
    # Use the validation partition from the original three-way split.
    resamples <- rsample::validation_set(data_split)
  } else {
    stop("Unsupported rsample split object: ", class(data_split)[1])
  }

  tune_res <- tune::tune_grid(
    wflow,
    resamples = resamples,
    grid = grid,
    control = tune::control_grid(save_pred = TRUE),
    metrics = yardstick::metric_set(
      yardstick::f_meas,
      yardstick::pr_auc,
      yardstick::spec,
      yardstick::sens,
      yardstick::bal_accuracy,
      yardstick::mcc
    )
  )

  return(tune_res)
}


#' selectBestModel()
#'
#' Selects best model by F1 score, AUPRC, MCC, or balanced accuracy.
#'
#' @param tune_res Results of grid tuning, such as the output of `tuneGrid()`
#' @param wflow A `workflows` object, such as the output of `buildWflow()`
#' @param select_best_metric [chr] Metric to select best model: "f_meas",
#' "pr_auc", "mcc", or "bal_accuracy"
#' @return Best model workflow
#' @examples
#' data(demo_ml_tibble)
#' data_split <- splitMLInputTibble(demo_ml_tibble, split = c(1, 0), seed = 1)
#' wflow <- buildWflow(
#'   buildLRModel(),
#'   buildRecipe(rsample::training(data_split))
#' )
#' set.seed(1)
#' tune_res <- tuneGrid(wflow, data_split,
#'   buildTuningGrid("LR", 10^c(-3, -1), c(0, 0.5, 1)),
#'   n_fold = 2
#' )
#' selectBestModel(tune_res, wflow, "mcc")
#' @export
selectBestModel <- function(tune_res, wflow, select_best_metric = "mcc") {
  .checkArgTuneRes(tune_res)
  .checkArgWflow(wflow)
  .checkArgSelectBestMetric(select_best_metric)

  best_mod <- tune::select_best(tune_res, metric = select_best_metric)
  final_mod <- tune::finalize_workflow(wflow, best_mod)

  return(final_mod)
}

#' fitBestModel()
#'
#' Fits the best model (output of `selectBestModel()`).
#'
#' @param final_mod Best model workflow (output of `selectBestModel()`)
#' @param train_data The part of the pangenome data designated for ML model
#' training. This can be the output of
#' `rsample::training(splitMLInputTibble(ml_input_tibble))`.
#' @return Best model fit
#' @examples
#' data(demo_ml_tibble)
#' data_split <- splitMLInputTibble(demo_ml_tibble, split = c(1, 0), seed = 1)
#' train <- rsample::training(data_split)
#' wflow <- buildWflow(buildLRModel(), buildRecipe(train))
#' set.seed(1)
#' tune_res <- tuneGrid(wflow, data_split,
#'   buildTuningGrid("LR", 10^c(-3, -1), c(0, 0.5, 1)),
#'   n_fold = 2
#' )
#' best_wflow <- selectBestModel(tune_res, wflow, "mcc")
#' fitBestModel(best_wflow, train)
#' @export
fitBestModel <- function(final_mod, train_data) {
  .checkArgWflow(final_mod)
  .checkArgTibble(train_data, ml = TRUE)

  fit <- final_mod |> parsnip::fit(data = train_data)

  return(fit)
}

#' .getFitHps()
#'
#' Returns the hyperparameters that were used to fit the best model.
#'
#' @param fit Best model fit, such as the output of `fitBestModel()`
#' @return Hyperparameters used to fit the final model
.getFitHps <- function(fit) {
  .checkArgWflow(fit)

  model <- class(fit$fit$actions$model$spec)[1]

  if (model %in% c("logistic_reg", "multinom_reg")) {
    penalty <- fit$fit$fit$spec$args$penalty

    mixture <- tryCatch(
      rlang::eval_tidy(fit$fit$fit$spec$args$mixture, data = list()),
      error = function(e) NA_real_
    )

    tibble::tibble(penalty = penalty, mixture = mixture)
  } else {
    stop("The `fit` object provided must correspond to 'logistic_reg' or 'multinom_reg'.")
  }
}

#' predictML()
#'
#' Predicts the AMR phenotype in the test data set based on the best fit ML
#' model.
#'
#' @param fit Best model fit, such as the output of `fitBestModel()`
#' @param test_data The part of the pangenome data designated for ML model
#' testing. This can be the output of
#' `rsample::testing(splitMLInputTibble(ml_input_tibble))`.
#' @return Test data (tibble) with an added column for predicted phenotype
#' labels
#' @examples
#' data(demo_ml_tibble)
#' data(demo_fit)
#' data_split <- splitMLInputTibble(demo_ml_tibble, split = c(1, 0), seed = 1)
#' predictML(demo_fit, rsample::testing(data_split))
#' @export
predictML <- function(fit, test_data) {
  .checkArgWflow(fit)
  .checkArgTibble(test_data, ml = TRUE)

  test_data_plus_predictions <- parsnip::augment(fit, test_data)

  return(test_data_plus_predictions)
}

#' getConfusionMatrix()
#'
#' Returns the confusion matrix based on the AMR phenotype predictions by an ML
#' model compared against the actual values.
#'
#' @param test_data_plus_predictions Test data (tibble) with an added column for
#' predicted phenotype labels, such as the output of `predictML()`
#' @return Confusion matrix of class `conf_mat`
#' @examples
#' preds <- tibble::tibble(
#'   genome_id = paste0("g", 1:8),
#'   genome_drug.resistant_phenotype = factor(
#'     rep(c("Resistant", "Susceptible"), each = 4),
#'     levels = c("Resistant", "Susceptible")
#'   ),
#'   .pred_class = factor(
#'     c(
#'       "Resistant", "Resistant", "Susceptible", "Resistant",
#'       "Susceptible", "Resistant", "Susceptible", "Susceptible"
#'     ),
#'     levels = c("Resistant", "Susceptible")
#'   )
#' )
#' getConfusionMatrix(preds)
#' @export
getConfusionMatrix <- function(test_data_plus_predictions) {
  .checkArgTestDataPlusPredictions(test_data_plus_predictions)

  target_var <- .getTargetVarName(test_data_plus_predictions)

  CM <- test_data_plus_predictions |>
    yardstick::conf_mat(truth = !!target_var, estimate = .pred_class)

  return(CM)
}

#' .calculatenMCC()
#'
#' Returns the normalized (to a 0 to 1 scale instead of -1 to 1) Matthews
#' correlation coefficient (nMCC) based on the AMR phenotype predictions by an
#' ML model compared against the actual values.
#'
#' @inheritParams getConfusionMatrix
#' @return Normalized (to a 0 to 1 scale instead of -1 to 1) Matthews
#' correlation coefficient (nMCC)
.calculatenMCC <- function(test_data_plus_predictions) {
  .checkArgTestDataPlusPredictions(test_data_plus_predictions)

  target_var <- .getTargetVarName(test_data_plus_predictions)

  mcc <- test_data_plus_predictions |>
    yardstick::mcc(truth = !!target_var, estimate = .pred_class) |>
    dplyr::select(.estimate) |>
    as.numeric()

  nmcc <- (mcc + 1) / 2

  return(round(nmcc, 2))
}

#' .calculateF1()
#'
#' Returns the F1 score based on the AMR phenotype predictions by an ML model
#' compared against the actual values.
#'
#' @inheritParams getConfusionMatrix
#' @return F1 score
.calculateF1 <- function(test_data_plus_predictions) {
  .checkArgTestDataPlusPredictions(test_data_plus_predictions)

  if (!("genome_drug.resistant_phenotype" %in%
    colnames(test_data_plus_predictions))) {
    stop(paste(
      "`test_data_plus_predictions` does not have a column for",
      "`genome_drug.resistant_phenotype`."
    ))
  }

  f1 <- test_data_plus_predictions |>
    yardstick::f_meas(
      truth = genome_drug.resistant_phenotype,
      estimate = .pred_class
    ) |>
    dplyr::select(.estimate) |>
    as.numeric() |>
    round(2)

  return(f1)
}

#' .calculateAUPRC()
#'
#' Returns the area under the precision-recall curve (AUPRC) based on the AMR
#' phenotype predictions by an ML model compared against the actual values.
#'
#' @inheritParams getConfusionMatrix
#' @return AUPRC
.calculateAUPRC <- function(test_data_plus_predictions) {
  .checkArgTestDataPlusPredictions(test_data_plus_predictions)

  if (!("genome_drug.resistant_phenotype" %in%
    colnames(test_data_plus_predictions))) {
    stop(paste(
      "`test_data_plus_predictions` does not have a column for",
      "`genome_drug.resistant_phenotype`."
    ))
  }

  auprc <- test_data_plus_predictions |>
    yardstick::pr_auc(
      truth = genome_drug.resistant_phenotype, .pred_Resistant
    ) |>
    dplyr::select(.estimate) |>
    as.numeric() |>
    round(2)

  return(auprc)
}

#' .calculateLog2APOP()
#'
#' Returns log2(AUPRC/prior) based on the AMR phenotype predictions by an ML
#' model compared against the actual values.
#'
#' @inheritParams getConfusionMatrix
#' @return log2(AUPRC/prior)
.calculateLog2APOP <- function(test_data_plus_predictions) {
  .checkArgTestDataPlusPredictions(test_data_plus_predictions)

  if (!("genome_drug.resistant_phenotype" %in%
    colnames(test_data_plus_predictions))) {
    stop(paste(
      "`test_data_plus_predictions` does not have a column for",
      "`genome_drug.resistant_phenotype`."
    ))
  }

  auprc <- .calculateAUPRC(test_data_plus_predictions)
  prior <- sum(
    test_data_plus_predictions$genome_drug.resistant_phenotype == "Resistant"
  ) /
    nrow(test_data_plus_predictions)

  if (prior > 0.3 && prior < 0.7) {
    warning(paste(
      "Classes are roughly balanced.",
      "Calculation of log2(AUPRC/prior) may be inappropriate."
    ))
  } else if (prior >= 0.7) {
    warning(paste(
      "Classes are imbalanced toward the resistant phenotype.",
      "Calculation of log2(AUPRC/prior) may be inappropriate."
    ))
  }

  log2_apop <- log2(auprc / prior) |> round(2)

  return(log2_apop)
}

#' .calculateBalAcc()
#'
#' Returns the balanced accuracy based on the AMR phenotype predictions by an
#' ML model compared against the actual values.
#'
#' @inheritParams getConfusionMatrix
#' @return Balanced accuracy
.calculateBalAcc <- function(test_data_plus_predictions) {
  .checkArgTestDataPlusPredictions(test_data_plus_predictions)

  if (!("genome_drug.resistant_phenotype" %in%
    colnames(test_data_plus_predictions))) {
    stop(paste(
      "`test_data_plus_predictions` does not have a column for",
      "`genome_drug.resistant_phenotype`."
    ))
  }

  bal_acc <- test_data_plus_predictions |>
    yardstick::bal_accuracy(
      truth = genome_drug.resistant_phenotype, estimate = .pred_class
    ) |>
    dplyr::select(.estimate) |>
    as.numeric() |>
    round(2)

  return(bal_acc)
}

#' .calculateSensitivity()
#'
#' Returns the sensitivity based on the AMR phenotype predictions by an ML model
#' compared against the actual values.
#'
#' @inheritParams getConfusionMatrix
#' @return sensitivity
.calculateSensitivity <- function(test_data_plus_predictions) {
  .checkArgTestDataPlusPredictions(test_data_plus_predictions)

  if (!("genome_drug.resistant_phenotype" %in%
    colnames(test_data_plus_predictions))) {
    stop(paste(
      "`test_data_plus_predictions` does not have a column for",
      "`genome_drug.resistant_phenotype`."
    ))
  }

  sens <- test_data_plus_predictions |>
    yardstick::sens(
      truth = genome_drug.resistant_phenotype,
      estimate = .pred_class
    ) |>
    dplyr::select(.estimate) |>
    as.numeric() |>
    round(2)

  return(sens)
}

#' .calculateSpecificity()
#'
#' Returns the specificity score based on the AMR phenotype predictions by an ML model
#' compared against the actual values.
#'
#' @inheritParams getConfusionMatrix
#' @return specificity
.calculateSpecificity <- function(test_data_plus_predictions) {
  .checkArgTestDataPlusPredictions(test_data_plus_predictions)

  if (!("genome_drug.resistant_phenotype" %in%
    colnames(test_data_plus_predictions))) {
    stop(paste(
      "`test_data_plus_predictions` does not have a column for",
      "`genome_drug.resistant_phenotype`."
    ))
  }

  spec <- test_data_plus_predictions |>
    yardstick::spec(
      truth = genome_drug.resistant_phenotype,
      estimate = .pred_class
    ) |>
    dplyr::select(.estimate) |>
    as.numeric() |>
    round(2)

  return(spec)
}

#' calculateEvalMets()
#'
#' Returns the F1 score, area under the precision-recall curve (AUPRC), balanced
#' accuracy, normalized (to a 0 to 1 scale instead of -1 to 1) Matthews
#' correlation coefficient (nMCC), and log2(AUPRC/prior) based on the AMR
#' phenotype predictions by an ML model compared against the actual values.
#'
#' @inheritParams getConfusionMatrix
#' @return F1 score, AUPRC, balanced accuracy, nMCC, and log2(AUPRC/prior)
#' @examples
#' preds <- tibble::tibble(
#'   genome_id = paste0("g", 1:10),
#'   genome_drug.resistant_phenotype = factor(
#'     rep(c("Resistant", "Susceptible"), each = 5),
#'     levels = c("Resistant", "Susceptible")
#'   ),
#'   .pred_class = factor(
#'     c(
#'       "Resistant", "Resistant", "Susceptible", "Resistant", "Susceptible",
#'       "Susceptible", "Resistant", "Susceptible", "Susceptible", "Resistant"
#'     ),
#'     levels = c("Resistant", "Susceptible")
#'   ),
#'   .pred_Resistant = c(0.9, 0.8, 0.4, 0.7, 0.3, 0.2, 0.6, 0.1, 0.2, 0.55),
#'   .pred_Susceptible = c(0.1, 0.2, 0.6, 0.3, 0.7, 0.8, 0.4, 0.9, 0.8, 0.45)
#' )
#' calculateEvalMets(preds)
#' @export
calculateEvalMets <- function(test_data_plus_predictions) {
  .checkArgTestDataPlusPredictions(test_data_plus_predictions)

  f1 <- .calculateF1(test_data_plus_predictions)
  auprc <- .calculateAUPRC(test_data_plus_predictions)
  bal_acc <- .calculateBalAcc(test_data_plus_predictions)
  sens <- .calculateSensitivity(test_data_plus_predictions)
  spec <- .calculateSpecificity(test_data_plus_predictions)
  nmcc <- .calculatenMCC(test_data_plus_predictions)
  log2_apop <- .calculateLog2APOP(test_data_plus_predictions)

  return(c(f1, auprc, bal_acc, nmcc, log2_apop))
}

#' extractTopFeats()
#'
#' Returns the top features that an ML model found to be important for
#' predicting the AMR phenotype of a given pathogen.
#'
#' @param fit Best model fit, such as the output of `fitBestModel()`
#' @param prop_vi_top_feats [num] A vector of length 2 with elements together
#' indicating the proportion of total variable importance the top features
#' should comprise. To get the features that contribute to the top 10 to 20% of
#' total variable importance, for example, set
#' `prop_vi_top_feats = c(0.1, 0.2)`.
#' Returns all features by default.
#' @param n_top_feats [num] Number of top features to extract
#' @return A tibble with a column for top features (`Variable`), a column for
#' `Importance`, and a column for `Sign` (or, for multi-class, a tibble with
#' per-class columns of importance scores for each `Variable`)
#' @examples
#' data(demo_fit)
#' extractTopFeats(demo_fit, n_top_feats = 10)
#' @export
extractTopFeats <- function(
  fit, prop_vi_top_feats = c(0, 1),
  n_top_feats = NA
) {
  .checkArgWflow(fit)

  if (!is.na(n_top_feats)) {
    prop_vi_top_feats <- NA
  }

  # Arg checking for every permutation of `prop_vi_top_feats` and `n_top_feats`
  if (is.na(n_top_feats) & any(!is.na(prop_vi_top_feats))) {
    .checkArgPropVITopFeats(prop_vi_top_feats)
  } else if (any(is.na(prop_vi_top_feats)) & !is.na(n_top_feats)) {
    .checkArgNTopFeats(n_top_feats)
  } else if (any(!is.na(prop_vi_top_feats)) & !is.na(n_top_feats)) {
    stop("Set either `n_top_feats` or `prop_vi_top_feats` to `NA` but not
      both.")
  } else if (any(is.na(prop_vi_top_feats)) & is.na(n_top_feats)) {
    stop("Please specify either `n_top_feats` or `prop_vi_top_feats`.")
  }

  feats_arranged <- fit |>
    workflowsets::extract_fit_parsnip() |>
    vip::vi() |>
    dplyr::arrange(dplyr::desc(Importance))

  if (!is.na(n_top_feats)) {
    top_feats_and_VIs <- feats_arranged |> dplyr::slice(1:n_top_feats)
  } else if (any(!is.na(prop_vi_top_feats))) {
    cum_vi_lower <- prop_vi_top_feats[1] * sum(feats_arranged$Importance)
    cum_vi_upper <- prop_vi_top_feats[2] * sum(feats_arranged$Importance)

    top_feats_and_VIs <- feats_arranged |>
      dplyr::mutate(cum_imp = cumsum(Importance)) |>
      dplyr::filter(cum_imp < cum_vi_upper & cum_imp > cum_vi_lower)
  }

  top_feat_tibble <- tibble::tibble(
    Variable = dplyr::pull(top_feats_and_VIs, Variable),
    Importance = dplyr::pull(top_feats_and_VIs, Importance),
    Sign = dplyr::pull(top_feats_and_VIs, Sign)
  )

  # Take a different approach if using multi-class (the previous code would give
  # a less meaningful result).
  if (is(fit$fit$actions$model$spec, "multinom_reg")) {
    warning(paste(
      "Extracting top features from a multi-class model.",
      "The `prop_vi_top_feats` and `n_top_feats` arguments do not apply."
    ))

    fit_penalty <- .getFitHps(fit)["penalty"] |> as.numeric()
    glmnet_fit <- parsnip::extract_fit_engine(fit)
    coefs <- stats::coef(glmnet_fit, s = fit_penalty)

    importance_table <- purrr::imap_dfr(coefs, function(mat, class) {
      mat_dense <- as.matrix(mat)
      tibble::tibble(
        class = class,
        Variable = rownames(mat_dense)[-1], # Exclude intercept.
        coefficient = mat_dense[-1, 1] # Get coefficients as numeric vector.
      )
    })

    top_feat_tibble <- importance_table |>
      dplyr::select(Variable, class, coefficient) |>
      tidyr::pivot_wider(
        names_from = class,
        values_from = coefficient,
        values_fill = 0 # Fill missing values with 0.
      ) |>
      dplyr::filter(dplyr::if_any(-Variable, ~ . != 0))
  }

  return(top_feat_tibble)
}
