# Global variables declaration to avoid R CMD check NOTEs for NSE
# (non-standard evaluation) variables used with dplyr/tidyr/ggplot2

# Package-level imports for packages used with :: notation
#' @importFrom jsonlite fromJSON write_json
#' @importFrom glmnet glmnet
#' @importFrom grDevices colorRampPalette
#' @importFrom stats median
#' @importFrom stats reorder
#' @importFrom stats sd
#' @keywords internal
"_PACKAGE"

utils::globalVariables(c(
  # Prediction columns from tidymodels
  ".estimate",
  ".pred_Resistant",
  ".pred_Susceptible",
  ".pred_class",

  # Variable importance columns
  "Importance",
  "Sign",
  "Variable",
  "coefficient",
  "cum_imp",

  # Data columns
  "abs_imp",
  "adj_p_value",
  "antibiotic",
  "bal_acc",
  "category",
  "class_abbr",
  "cluster",
  "contribution",
  "diff_top2",
  "drug",
  "drug_abbr",
  "drug_class",
  "drug_label",
  "drug_or_class",
  "feature",
  "feature_id",
  "feature_subtype",
  "feature_type",
  "filename",
  "fit_min_n",
  "fit_mixture",
  "fit_mtry",
  "fit_trees",
  "fname",
  "gene",
  "genome_drug.antibiotic",
  "genome.genome_id",
  "genome_drug.resistant_phenotype",
  "genome_id",
  "i_sparse",
  "i_strat",
  "idx_cross",
  "idx_leaveout",
  "idx_sparse",
  "idx_strat",
  "label",
  "model",
  "neg_log10_adj_p",
  "mcc",
  "mean_margin",
  "median_mcc",
  "n_feat_types",
  "nmcc",
  "num_obs",
  "seed",
  "sens",
  "spec",
  "output_prefix",
  "p_value",
  "pair_id",
  "parts",
  "phenotype",
  "proteinName",
  "precision",
  "prefix",
  "prefix_key",
  "prop",
  "recall",
  "ref_drug",
  "ref_file",
  "res_prop",
  "resistant_classes",
  "run_time_sec",
  "shuffled",
  "shuffled_label",
  "sig_after_bh",
  "significance",
  "strat_value",
  "strat_value_test",
  "stratification",
  "test_country",
  "test_drug",
  "test_file",
  "test_year",
  "tested_on",
  "total",
  "train_country",
  "train_prop",
  "train_year",
  "value",

  # feature_rescoring.R (computeFeatureScore / computeFeatureImprovement)
  "best_rank",
  "contrib_score",
  "coverage_boost",
  "delta_rank",
  "delta_score",
  "denom",
  "expected_types",
  "feature_cluster_parquet",
  "fully_realized_scales",
  "good_feature",
  "improvement",
  "max_imp",
  "mean_rank",
  "mean_rank_nonshuffle",
  "mean_rank_score",
  "mean_rank_shuffle",
  "median_contribution",
  "median_datatype",
  "median_drug_or_class",
  "median_rank",
  "min_imp",
  "n_features",
  "n_scales",
  "observed_types_csv",
  "partially_realized_scales",
  "range_imp",
  "rank_score",
  "realization_score",
  "scale_factor",
  "scale_realization",
  "sign_consistent",
  "species",
  "stability_score",

  # Base R functions that need explicit import
  "barplot",
  "reformulate"
))
