# This script houses functions for iterative feature elimination (IFE).

#' @importFrom dplyr all_of
#' @importFrom dplyr filter
#' @importFrom dplyr mutate
#' @importFrom dplyr pull
#' @importFrom dplyr select
#' @importFrom tibble tibble
NULL

#' removeTopFeats
#'
#' Removes top features from a pangenome given previous ML results.
#'
#' @param ml_input_tibble An ML-ready tibble generated by `loadMLInputTibble()`
#' @param top_feat_tibble Second element of the list output of
#' `runMLPipeline()`, containing all features to be removed from the
#' `ml_input_tibble`
#' @return An amR pangenome with top features removed
#' @examples
#' ml <- tibble::tibble(
#'   genome_id = paste0("g", 1:6),
#'   genome_drug.resistant_phenotype = rep(c("Resistant", "Susceptible"), each = 3),
#'   feat_a = c(1L, 0L, 1L, 0L, 1L, 0L),
#'   feat_b = c(0L, 1L, 0L, 1L, 0L, 1L),
#'   feat_c = c(1L, 1L, 0L, 0L, 1L, 0L)
#' )
#' top <- tibble::tibble(Variable = c("feat_a", "feat_c"))
#' removeTopFeats(ml, top)
#' @export
removeTopFeats <- function(ml_input_tibble, top_feat_tibble) {
  .checkArgTibble(ml_input_tibble)

  feats_to_remove <- top_feat_tibble |> dplyr::pull(Variable)

  if (length(feats_to_remove) == 0) {
    stop(
      "No more feats to remove; try adjusting `percent_removal_vec` ",
      "in `runIFE()` to include a wider range between percentages."
    )
  }

  ml_input_tibble_top_feats_removed <- ml_input_tibble |>
    dplyr::select(-dplyr::all_of(feats_to_remove))

  return(ml_input_tibble_top_feats_removed)
}

#' runIFE
#' Removes top features identified by ML models and retrains iteratively;
#' returns MCC at each iteration.
#'
#' @param ml_input_tibble An ML-ready tibble generated by `loadMLInputTibble()`
#' @param by_num [bool] Set to `TRUE` if removing top features as a percentage
#' of the total number of features.
#' @param by_vi [bool] Set to `TRUE` if removing top features by their
#' contribution to the total variable importance.
#' @param percent_removal_vec [num] A vector of percentages of total top
#' features removed (if `by_num = TRUE` and `by_vi = FALSE`) or percent
#' contributions of top features removed to the total variable importance (if
#' `by_vi = TRUE` and `by_num = FALSE`) at each iteration. The function will
#' automatically train with all features to start, so there is no need to
#' specify 0 in this vector.
#' @param mix_vec [num] A vector containing mixture values (0 corresponds
#' to L2 regularization; 1 corresponds to L1; intermediate values correspond to
#' elastic net) to try. The default corresponds to L2 for the purpose of IFE
#' analysis.
#' @param return_feats [bool] Whether to return top features from each iteration
#' of IFE.
#' @param verbose [bool] The function will stay quiet if set to `FALSE`.
#' @return A tibble with IFE performance (note: this will be returned within a
#' list along with top features removed per iteration if `return_feats = TRUE`.)
#' @examples
#' data(demo_ml_tibble)
#' set.seed(1)
#' runIFE(
#'   demo_ml_tibble,
#'   by_num = TRUE, by_vi = FALSE,
#'   percent_removal_vec = c(25, 50), mix_vec = 0,
#'   return_feats = TRUE, verbose = FALSE
#' )
#' @export
runIFE <- function(
  ml_input_tibble, by_num = TRUE, by_vi = FALSE,
  percent_removal_vec = 10 * 1:9, mix_vec = 0, return_feats = FALSE,
  verbose = TRUE
) {
  .checkArgByNum(by_num)
  .checkArgByVI(by_vi)
  .checkArgPercentRemovalVec(percent_removal_vec)
  .checkArgReturnFeats(return_feats)
  .checkArgVerbose(verbose)

  if (sum(c(by_num, by_vi)) != 1) {
    stop(
      "Set either `by_num` or `by_vi` to `TRUE` and the other to ",
      "`FALSE` (not both `TRUE` or both `FALSE`)."
    )
  }

  # Create empty objects to store results.
  num_obs_vec <- c()
  res_prop_vec <- c()
  fit_mixture_vec <- c()
  mcc_vec <- c()
  nmcc_vec <- c()
  n_feats_removed_vec <- c()
  total_feats_removed_vec <- c()
  run_time_vec <- c()
  feats_removed_list <- list()

  total_n_feat <- getNumFeat(ml_input_tibble)

  # Note: `prop_vi_top_feats_actual` represents the values used for IFE
  # (if `by_vi = TRUE`) whereas `prop_vi_top_feats_ml` is the value that goes
  # into `runMLPipeline()` and does not reflect the top features removed at each
  # step of the IFE process.
  if (verbose) {
    message("Training with all features")
  }

  for (i in seq_len(length(percent_removal_vec) + 1)) {
    if (i == 1) {
      n_feats_removed <- 0
    }

    if (by_vi) {
      # We will extract all top features at the first iteration, and these
      # will be removed one set at a time in subsequent iterations. Past the
      # first iteration, set `n_top_feats` to 1 (this is arbitrary) to minimize
      # memory cost.
      if (i == 1) {
        prop_vi_top_feats_ml <- c(0, 1)
        n_top_feats <- NA
      } else {
        prop_vi_top_feats_ml <- NA
        n_top_feats <- 1
      }
    }

    if (by_num) {
      # Get the number of top features that will be returned by the ML
      # pipeline this iteration (and removed for the next iteration).
      if (i == 1) {
        n_top_feats <- round(total_n_feat * percent_removal_vec[i] / 100)
      } else if (i == length(percent_removal_vec) + 1) {
        n_top_feats <- 1 # Arbitrary number for the last iteration
      } else {
        n_top_feats <-
          round(total_n_feat * percent_removal_vec[i] / 100) -
          round(total_n_feat * percent_removal_vec[i - 1] / 100)
      }
      prop_vi_top_feats_ml <- NA
    }

    ml_res <- tryCatch(runMLPipeline(ml_input_tibble,
      prop_vi_top_feats = prop_vi_top_feats_ml, n_top_feats = n_top_feats,
      mix_vec = mix_vec, verbose = FALSE
    ), error = function(e) {
      NULL
    })

    if (is.null(ml_res)) {
      break
    }

    # Add results to corresponding vectors.
    num_obs_vec[i] <- ml_res$performance_tibble |>
      dplyr::select(num_obs) |>
      as.numeric()
    res_prop_vec[i] <- ml_res$performance_tibble |>
      dplyr::select(res_prop) |>
      as.numeric()
    fit_mixture_vec[i] <- ml_res$performance_tibble |>
      dplyr::select(fit_mixture) |>
      as.numeric()
    mcc_vec[i] <- ml_res$performance_tibble |>
      dplyr::select(mcc) |>
      as.numeric()
    nmcc_vec[i] <- ml_res$performance_tibble |>
      dplyr::select(nmcc) |>
      as.numeric()
    n_feats_removed_vec[i] <- n_feats_removed

    if (i == 1) {
      total_feats_removed_vec[i] <- 0
    } else {
      total_feats_removed_vec[i] <- n_feats_removed +
        total_feats_removed_vec[i - 1]
    }

    run_time_vec[i] <- ml_res$performance_tibble |>
      dplyr::select(run_time_sec) |>
      as.numeric()

    if (i == (length(percent_removal_vec) + 1)) {
      break
    }

    if (by_vi) {
      if (i == 1) {
        # Store results tibble from first iteration that has all top features
        # and their VI scores.
        ml_res_all <- ml_res

        total_vi <- sum(ml_res_all$top_feat_tibble$Importance)

        # This will correspond to the proportion removed for the next
        # iteration
        prop_vi_top_feats_actual <- c(0, percent_removal_vec[i] / 100)
      } else {
        prop_vi_top_feats_actual <- c(
          percent_removal_vec[i - 1],
          percent_removal_vec[i]
        ) / 100
      }
      cum_vi_lower <- prop_vi_top_feats_actual[1] * total_vi
      cum_vi_upper <- prop_vi_top_feats_actual[2] * total_vi

      feats_to_remove_tibble <- ml_res_all$top_feat_tibble |>
        dplyr::mutate(cum_imp = cumsum(Importance)) |>
        dplyr::filter(cum_imp < cum_vi_upper & cum_imp > cum_vi_lower)
    }

    n_feat_start <- getNumFeat(ml_input_tibble)

    # Removal of top features
    if (by_vi) {
      if (verbose) {
        message(
          "Cumulatively removed top ",
          percent_removal_vec[i], "% of total variable importance"
        )
      }
      ml_input_tibble <- ml_input_tibble |>
        removeTopFeats(feats_to_remove_tibble)
    } else if (by_num) {
      if (verbose) {
        message(
          "Cumulatively removed top ",
          percent_removal_vec[i], "% of all features"
        )
      }
      feats_to_remove_tibble <- ml_res$top_feat_tibble

      ml_input_tibble <- ml_input_tibble |>
        removeTopFeats(feats_to_remove_tibble)
    }
    if (return_feats) {
      feats_removed_list[[paste("cum_perc_removed_", percent_removal_vec[i],
        sep = ""
      )]] <- dplyr::pull(feats_to_remove_tibble, Variable)
    }

    n_feat_end <- getNumFeat(ml_input_tibble)
    n_feats_removed <- n_feat_start - n_feat_end
  }

  if (by_vi) {
    removal_type <- "by_vi"
  } else if (by_num) {
    removal_type <- "by_num"
  }

  # Adjust `percent_removal_vec` to appropriate length (if IFE stopped running
  # early due to encountering an error).
  percent_removal_vec <- percent_removal_vec[seq_len(length(num_obs_vec) - 1)]

  ife_performance_tibble <- tibble::tibble(
    percent_removed = c(0, percent_removal_vec),
    removal_type = rep(removal_type, length(num_obs_vec)),
    num_obs = num_obs_vec, res_prop = res_prop_vec,
    fit_mixture = fit_mixture_vec, mcc = mcc_vec, nmcc = nmcc_vec,
    n_feats_removed = n_feats_removed_vec,
    total_feats_removed = total_feats_removed_vec, run_time_sec = run_time_vec
  )

  if (return_feats) {
    all_results <- list(
      ife_performance_tibble = ife_performance_tibble,
      feats_removed = feats_removed_list
    )
  } else {
    return(ife_performance_tibble)
  }
}
