# This script contains functions to prepare an amR pangenome for ML, starting
# with a Parquet file. It also has functions to calculate relevant metrics,
# such as the number of features in the pangenome.


# Provide local logger for ML prep just like data_curation and data_processing
.ml_logger <- function(verbosity = c("minimal", "debug")) {
  .make_logger(match.arg(verbosity))
}

# Adding a helper to read in the .json file that defines the matrix generation
# parameters, including how data are split

#' @keywords internal
.readMLParameters <- function(matrix_dir) {
  stopifnot(length(matrix_dir) == 1)
  matrix_dir <- normalizePath(matrix_dir)

  candidates <- c(
    file.path(matrix_dir, "ml_parameters.json"),
    file.path(dirname(matrix_dir), "ml_parameters.json")
  )

  found <- candidates[file.exists(candidates)]

  log <- .ml_logger("minimal")
  if (length(found) == 0) {
    log("info", paste0("No ml_parameters.json found in: ", matrix_dir, " or its parent."))
    return(NULL)
  }

  params <- jsonlite::fromJSON(found[1])

  # Basic structure checks
  if (is.null(params$split) || length(params$split) != 2) {
    stop("`ml_parameters.json` is missing a valid `split` (length-2 numeric).")
  }
  if (!is.null(params$mode) && !params$mode %in% c("cv", "splits")) {
    stop("`ml_parameters.json` has invalid `mode`; expected 'cv' or 'splits'.")
  }
  if (!is.null(params$seed) && !is.numeric(params$seed)) {
    stop("`ml_parameters.json` `seed` must be numeric if present.")
  }
  if (!is.null(params$n_fold) && !is.numeric(params$n_fold)) {
    stop("`ml_parameters.json` `n_fold` must be numeric if present.")
  }

  params
}

# Read the output matrix paths to find the .json for .readMLParameters()
#' @keywords internal
.matrixDirFromParquet <- function(parquet_path) {
  .checkArgPath(parquet_path)
  normalizePath(dirname(parquet_path))
}

#' @importFrom arrow read_parquet
#' @importFrom dplyr all_of
#' @importFrom dplyr mutate
#' @importFrom dplyr pull
#' @importFrom rlang :=
#' @importFrom rlang sym
#' @importFrom tidyr pivot_wider
NULL

#' loadMLInputTibble()
#'
#' Reads in a Parquet file as a tibble and converts it from long to wide format
#' to prepare it for ML.
#'
#' @param parquet_path [chr] Path to a long-format sparse Parquet file from
#' upstream processing.
#' @returns A tibble (one row per genome, one column per feature), plus
#' "Resistant" or "Susceptible" AMR phenotype labels
#' @export
loadMLInputTibble <- function(parquet_path) {
  .checkArgPath(parquet_path)

  long_tibble <- arrow::read_parquet(parquet_path)

  if (!xor(
    "genome_drug.resistant_phenotype" %in% colnames(long_tibble),
    "resistant_classes" %in% colnames(long_tibble)
  )) {
    stop(paste(
      "The tibble loaded from `parquet_path` must have a target",
      "variable column named either `genome_drug.resistant_phenotype` or",
      "`resistant_classes`, but not both."
    ))
  }

  if (!all(c("genome_id", "feature_id", "value") %in% colnames(long_tibble))) {
    stop(paste(
      "The data is missing one or more of the following required",
      "columns: 'genome_id', 'feature_id', 'value'."
    ))
  }

  target_var <- .getTargetVarName(long_tibble)

  ml_input_tibble <- long_tibble |>
    dplyr::mutate(!!target_var := as.factor(!!target_var)) |>
    tidyr::pivot_wider(
      id_cols = dplyr::all_of(
        c("genome_id", as.character(target_var))
      ),
      names_from = feature_id, values_from = value, values_fill = 0
    )


  if (exists(".ml_logger")) {
    log <- .ml_logger("minimal")
    log("debug", paste0("ML tibble constructed: ", nrow(ml_input_tibble),
                        " genomes × ", getNumFeat(ml_input_tibble), " features"))
  }

  if (anyDuplicated(dplyr::pull(ml_input_tibble, genome_id)) != 0) {
    stop("Non-unique genome IDs found when constructing the ML input tibble.")
  }

  return(ml_input_tibble)
}

#' getNumFeat()
#'
#' Returns the number of features in an amR pangenome.
#'
#' @param ml_input_tibble An ML-ready tibble generated by `loadMLInputTibble()`.
#' This must have a target variable column named either
#' `genome_drug.resistant_phenotype` ("Resistant" or "Susceptible "
#' classification for one bug/drug combination) or `resistant_classes`
#' (multi-class classification for determining the drug classes to which each
#' genome is resistant), but not both.
#' @return Number of features
#' @export
getNumFeat <- function(ml_input_tibble) {
  .checkArgTibble(ml_input_tibble, ml = TRUE)

  # A vector that, for each column in a pangenome, contains `TRUE` if the column
  # is a feature and `FALSE` if it is not.
  feature_tf_vec <- !grepl("^genome", colnames(ml_input_tibble))

  n_feat <- sum(feature_tf_vec)

  # If `ml_input_tibble` contains `resistant_classes` as a target variable
  # instead of `genome_drug.resistant_phenotype`, the above code will still
  # count this column as a feature since "genome" is not contained in the name,
  # so subtract 1 if this is the case.
  if (as.character(.getTargetVarName(ml_input_tibble)) == "resistant_classes") {
    n_feat <- n_feat - 1
  }

  return(n_feat)
}

#' shuffleLabels()
#'
#' Randomly shuffles the AMR phenotype labels in the ML-ready tibble.
#'
#' @param ml_input_tibble An ML-ready tibble generated by `loadMLInputTibble()`.
#' This must have a target variable column named either
#' `genome_drug.resistant_phenotype` ("Resistant" or "Susceptible "
#' classification for one bug/drug combination) or `resistant_classes`
#' (multi-class classification for determining the drug classes to which each
#' genome is resistant), but not both.
#' @param seed [num] For reproducible analysis
#' @return Pangenome with randomly shuffled AMR phenotype labels
#' @export
shuffleLabels <- function(ml_input_tibble, seed = 5280) {
  .checkArgTibble(ml_input_tibble, ml = TRUE)
  .checkArgSeed(seed)

  set.seed(seed)
  target_var <- .getTargetVarName(ml_input_tibble)

  log <- .ml_logger("debug")
  log("debug", "Shuffling phenotype labels (for baseline models).")

  ml_input_tibble |>
    dplyr::mutate(!!target_var := sample(!!target_var))
}


#' @rdname .calculateMinSamples
#' @export
.calculateMinSamples <- function(n_fold, split, res_prop, smallest_n_obs_rs = 1) {
  # Using the same logic from upstream matrix generation
  base <- .calculateMinSamples(n_fold = n_fold, split = split, res_prop = res_prop)
  ceiling(base * smallest_n_obs_rs)
}

#' .getTargetVarName()
#'
#' Returns the name of the target variable to be used for machine learning:
#' either `genome_drug.resistant_phenotype` or `resistant_classes`
#'
#' @param ml_input_tibble An ML-ready tibble generated by `loadMLInputTibble()`.
#' This must have a target variable column named either
#' `genome_drug.resistant_phenotype` ("Resistant" or "Susceptible "
#' classification for one bug/drug combination) or `resistant_classes`
#' (multi-class classification for determining the drug classes to which each
#' genome is resistant), but not both.
#' @return The name of the target variable to be used for machine learning:
#' either `rlang::sym("genome_drug.resistant_phenotype")` or
#' `rlang::sym("resistant_classes")`
#' @export
.getTargetVarName <- function(ml_input_tibble) {
  .checkArgTibble(ml_input_tibble, ml = TRUE)

  if ("genome_drug.resistant_phenotype" %in% colnames(ml_input_tibble)) {
    target_var <- "genome_drug.resistant_phenotype"
  } else if ("resistant_classes" %in% colnames(ml_input_tibble)) {
    target_var <- "resistant_classes"
  }

  return(rlang::sym(target_var))
}
