# This script contains functions to prepare an amR pangenome for ML, starting
# with a Parquet file. It also has functions to calculate relevant metrics,
# such as the number of features in the pangenome.

#' @importFrom arrow read_parquet
#' @importFrom dplyr all_of
#' @importFrom dplyr mutate
#' @importFrom dplyr pull
#' @importFrom rlang :=
#' @importFrom rlang sym
#' @importFrom tidyr pivot_wider
NULL

#' loadMLInputTibble()
#'
#' Reads in a Parquet file as a tibble and converts it from long to wide format
#' to prepare it for ML.
#'
#' @param parquet_path [chr] Path to a long-format sparse Parquet file from
#' upstream processing.
#' @returns A tibble (one row per genome, one column per feature), plus
#' "Resistant" or "Susceptible" AMR phenotype labels
#' @export
loadMLInputTibble <- function(parquet_path) {
  .checkArgPath(parquet_path)

  long_tibble <- arrow::read_parquet(parquet_path)

  if (!xor(
    "genome_drug.resistant_phenotype" %in% colnames(long_tibble),
    "resistant_classes" %in% colnames(long_tibble)
  )) {
    stop(paste(
      "The tibble loaded from `parquet_path` must have a target",
      "variable column named either `genome_drug.resistant_phenotype` or",
      "`resistant_classes`, but not both."
    ))
  }

  if (!all(c("genome_id", "feature_id", "value") %in% colnames(long_tibble))) {
    stop(paste(
      "The data is missing one or more of the following required",
      "columns: 'genome_id', 'feature_id', 'value'."
    ))
  }

  target_var <- getTargetVarName(long_tibble)

  ml_input_tibble <- long_tibble |>
    dplyr::mutate(!!target_var := as.factor(!!target_var)) |>
    tidyr::pivot_wider(
      id_cols = dplyr::all_of(
        c("genome_id", as.character(target_var))
      ),
      names_from = feature_id, values_from = value, values_fill = 0
    )

  if (anyDuplicated(dplyr::pull(ml_input_tibble, genome_id)) != 0) {
    stop("Non-unique genome IDs found when constructing the ML input tibble.")
  }

  return(ml_input_tibble)
}

#' getNumFeat()
#'
#' Returns the number of features in an amR pangenome.
#'
#' @param ml_input_tibble An ML-ready tibble generated by `loadMLInputTibble()`.
#' This must have a target variable column named either
#' `genome_drug.resistant_phenotype` ("Resistant" or "Susceptible "
#' classification for one bug/drug combination) or `resistant_classes`
#' (multi-class classification for determining the drug classes to which each
#' genome is resistant), but not both.
#' @return Number of features
#' @export
getNumFeat <- function(ml_input_tibble) {
  .checkArgTibble(ml_input_tibble, ml = TRUE)

  # A vector that, for each column in a pangenome, contains `TRUE` if the column
  # is a feature and `FALSE` if it is not.
  feature_tf_vec <- !grepl("^genome", colnames(ml_input_tibble))

  n_feat <- sum(feature_tf_vec)

  # If `ml_input_tibble` contains `resistant_classes` as a target variable
  # instead of `genome_drug.resistant_phenotype`, the above code will still
  # count this column as a feature since "genome" is not contained in the name,
  # so subtract 1 if this is the case.
  if (getTargetVarName(ml_input_tibble) == "resistant_classes") {
    n_feat <- n_feat - 1
  }

  return(n_feat)
}

#' shuffleLabels()
#'
#' Randomly shuffles the AMR phenotype labels in the ML-ready tibble.
#'
#' @param ml_input_tibble An ML-ready tibble generated by `loadMLInputTibble()`.
#' This must have a target variable column named either
#' `genome_drug.resistant_phenotype` ("Resistant" or "Susceptible "
#' classification for one bug/drug combination) or `resistant_classes`
#' (multi-class classification for determining the drug classes to which each
#' genome is resistant), but not both.
#' @param seed [num] For reproducible analysis
#' @return Pangenome with randomly shuffled AMR phenotype labels
#' @export
shuffleLabels <- function(ml_input_tibble, seed = 123) {
  .checkArgTibble(ml_input_tibble, ml = TRUE)
  .checkArgSeed(seed)

  set.seed(seed)

  target_var <- getTargetVarName(ml_input_tibble)

  ml_input_tibble_shuffled_labels <- ml_input_tibble |>
    dplyr::mutate(!!target_var := sample(!!target_var))

  return(ml_input_tibble_shuffled_labels)
}

#' calculateMinSamples()
#'
#' Returns the minimum number of total observations needed (one bug-drug combo)
#' to have at least `smallest_n_obs_rs` observations (default is 1) of each
#' class in each fold of cross-validation.
#'
#' @param n_fold [num] Number of folds of cross-validation. This will be ignored
#' if the second element of the `split` argument is non-zero (indicating that
#' a validation set is being used rather than cross-validation).
#' @param split [num] Vector of length 2 indicating the proportion of data to
#' be designated as training and validation, respectively.
#' @param res_prop [num] The proportion of antibiotic resistant genomes
#' @return Minimum number of total observations needed (one bug-drug combo)
#' to have at least one observation of each class in each fold of
#' cross-validation
#' @param smallest_n_obs_rs [num] The smallest number of "Resistant" or
#' "Susceptible" observations allowable in the smallest subset of data used
#' during ML.
#' @export
calculateMinSamples <- function(
  n_fold, split, res_prop,
  smallest_n_obs_rs = 1
) {
  .checkArgSplit(split)
  .checkArgResProp(res_prop)
  .checkArgSmallestNObsRS(smallest_n_obs_rs)

  # Designate `lowest_prop` as the phenotype ("Resistant" or "Susceptible") in
  # lower proportion.
  if (res_prop <= 0.5) {
    lowest_prop_rs <- res_prop
  } else {
    lowest_prop_rs <- 1 - res_prop
  }

  if (split[2] == 0) { # If using cross-validation...
    # If a single fold of cross-validation has fewer observations than the test
    # data, calculate `min_samples` based on this. Otherwise, calculate it based
    # on the test data.
    .checkArgNFold(n_fold)

    if (1 - split[1] >= split[1] / n_fold) {
      min_samples <- n_fold / (lowest_prop_rs * split[1])
    } else {
      min_samples <- 1 / (lowest_prop_rs * (1 - split[1]))
    }
  } else { # If using a validation set...
    lowest_prop_tvt <- min(split[1], split[2], 1 - split[1] - split[2])

    min_samples <- 1 / (lowest_prop_rs * lowest_prop_tvt)
  }

  min_samples <- min_samples * smallest_n_obs_rs

  return(ceiling(min_samples))
}

#' getTargetVarName()
#'
#' Returns the name of the target variable to be used for machine learning:
#' either `genome_drug.resistant_phenotype` or `resistant_classes`
#'
#' @param ml_input_tibble An ML-ready tibble generated by `loadMLInputTibble()`.
#' This must have a target variable column named either
#' `genome_drug.resistant_phenotype` ("Resistant" or "Susceptible "
#' classification for one bug/drug combination) or `resistant_classes`
#' (multi-class classification for determining the drug classes to which each
#' genome is resistant), but not both.
#' @return The name of the target variable to be used for machine learning:
#' either `rlang::sym("genome_drug.resistant_phenotype")` or
#' `rlang::sym("resistant_classes")`
#' @export
getTargetVarName <- function(ml_input_tibble) {
  .checkArgTibble(ml_input_tibble, ml = TRUE)

  if ("genome_drug.resistant_phenotype" %in% colnames(ml_input_tibble)) {
    target_var <- "genome_drug.resistant_phenotype"
  } else if ("resistant_classes" %in% colnames(ml_input_tibble)) {
    target_var <- "resistant_classes"
  }

  return(rlang::sym(target_var))
}
