# This script houses the runMLPipeline() function.

#' @importFrom dplyr bind_rows
#' @importFrom dplyr count
#' @importFrom dplyr filter
#' @importFrom dplyr mutate
#' @importFrom dplyr pull
#' @importFrom dplyr rename
#' @importFrom dplyr select
#' @importFrom rsample testing
#' @importFrom rsample training
#' @importFrom tibble add_column
#' @importFrom tibble is_tibble
#' @importFrom tibble tibble
NULL

#' runMLPipeline()
#'
#' Stitches together core ML functions into one pipeline.
#'
#' @param ml_input_tibble An ML-ready tibble generated by `loadMLInputTibble()`.
#' This must have a target variable column named either
#' `genome_drug.resistant_phenotype` ("Resistant" or "Susceptible "
#' classification for one bug/drug combination) or `resistant_classes`
#' (multi-class classification for determining the drug classes to which each
#' genome is resistant), but not both.
#' @param model [chr] Logistic regression ("LR")
#' @param split [num] Vector of length 2 indicating the proportion of data to
#' be designated as training and validation, respectively. Note: if `test_data`
#' is provided, these numbers will be scaled so that they sum to 1 and will
#' still represent fractions of `ml_input_tibble` (not including the input
#' `test_data`). Please do not directly provide numbers that sum to 1 since the
#' function is not equipped to handle this. If cross-validation is enabled here
#' `split = c(1,0)`, we will still retain a 20% test holdout for final reporting.
#' Cross-validation is run on the 80% training portion, and not on the testing set.
#' @param n_fold [num] Number of folds of cross-validation
#' @param prop_vi_top_feats [num] A vector of length 2 with elements together
#' indicating the proportion of total variable importance the top features
#' should comprise. To get the features that contribute to the top 10 to 20% of
#' total variable importance, for example,
#' `set prop_vi_top_feats = c(0.1, 0.2)`. Returns all features by default.
#' @param n_top_feats [num] Number of top features to extract per drug
#' @param use_pca [bool] Set to `TRUE` to use PCA instead of all features.
#' @param pca_threshold [num] The proportion of total variance for which the
#' principle components account
#' @param penalty_vec [num] A vector containing `penalty` (regularization
#' strength) values to try (for logistic regression). It is recommended to
#' choose values `10^-4` to `10^4`.
#' @param mix_vec [num] A vector containing `mixture` values to try for logistic
#' regression. 0 corresponds to L2 regularization; 1 corresponds to L1;
#' intermediate values correspond to elastic net.
#' @param min_n_vec \[num\] A vector containing `min_n` values (the number of data
#' points in a node required for the node to be split) to try for random forest
#' or boosted tree. It is recommended to choose values in the range 1 to 100.
#' @param tree_vec \[num\] A vector containing values to try for the number of
#' `trees` in random forest or boosted tree. It is recommended to choose values
#' in the range 100 to 1000.
#' @param select_best_metric [chr] Metric to select best model: "f_meas",
#' "pr_auc", or "bal_accuracy"
#' @param seed [num] For reproducible analysis
#' @param shuffle_labels [bool] Set to `TRUE` to randomly shuffle AMR phenotype
#' labels for baseline comparisons.
#' @param test_data A tibble to use as testing data instead of a subset of
#' `ml_input_tibble`. This can be useful for testing different geographical
#' or temporal holdouts. The `split` argument still tells how `ml_input_tibble`
#' should be divided for training and validation.
#' @param return_tune_res [bool] Set to `TRUE` to return tuning results.
#' @param return_fit [bool] Set to `TRUE` to return the model `fit`.
#' @param return_pred [bool] Set to `TRUE` to return the predicted and actual
#' AMR phenotypes.
#' @param verbose [bool] The function will stay quiet if set to `FALSE`.
#' @return A list with two elements: A `performance_tibble` and a
#' `top_feat_tibble`. Tuning results, the fit object, and model predictions may
#' also be returned if `return_tune_res`, `return_fit`, and/or `return_pred`,
#' respectively, are set to `TRUE`.
#' @examples
#' data(demo_ml_tibble)
#' set.seed(1)
#' runMLPipeline(
#'   ml_input_tibble = demo_ml_tibble, model = "LR",
#'   split = c(1, 0), n_fold = 2,
#'   penalty_vec = 10^c(-3, -1), mix_vec = c(0, 0.5, 1),
#'   n_top_feats = 10, verbose = FALSE
#' )
#' @export
runMLPipeline <- function(
  ml_input_tibble, model = "LR", split = c(0.6, 0.2),
  n_fold = 2, prop_vi_top_feats = c(0, 1), n_top_feats = NA, use_pca = FALSE,
  pca_threshold = 0.95, penalty_vec = 10^seq(-4, -1, length.out = 10),
  mix_vec = 0:5 / 5, min_n_vec = c(2, 6, 12), tree_vec = c(100, 500, 1000),
  select_best_metric = "mcc", seed = 123, shuffle_labels = FALSE,
  test_data = NA, return_tune_res = FALSE, return_fit = FALSE,
  return_pred = FALSE, verbose = TRUE
) {
  start_time <- Sys.time()

  .checkArgShuffleLabels(shuffle_labels)
  .checkArgVerbose(verbose)
  .checkArgReturnTuneRes(return_tune_res)
  .checkArgReturnFit(return_fit)
  .checkArgReturnPred(return_pred)
  .checkArgSeed(seed)

  # Seed once for the whole pipeline so the split, CV folds, tuning, and fit
  # share one continuous RNG stream (restored to the caller's state on exit).
  withr::local_seed(seed)

  # Set `n_fold` to `NA` if not using cross-validation.
  if (split[2] != 0) {
    n_fold <- NA
  }

  # Confirm resolved split params
  if (verbose) {
    mode <- if (split[2] == 0) "cv" else "splits"
    message(sprintf(
      "ML split mode: %s | split = c(%.2f, %.2f) | n_fold = %s | seed = %s",
      mode, split[1], split[2],
      ifelse(is.na(n_fold), "NA", as.character(n_fold)),
      as.character(seed)
    ))
  }

  # Create a variable indicating whether external `test_data` was provided. This
  # will be set to `TRUE` later if the `test_data` argument is not `NA`.
  external_test_data <- FALSE

  num_obs_ml_input_tibble <- nrow(ml_input_tibble)

  # Determine whether multi-class classification is to be performed.
  if (as.character(.getTargetVarName(ml_input_tibble)) == "resistant_classes") {
    multi_class <- TRUE
  } else {
    multi_class <- FALSE
  }

  if (model != "LR" & multi_class) {
    stop(
      "Multi-class classification can be performed only with ",
      "logistic regression in our current implementation."
    )
  }

  if (verbose) {
    message(
      "`ml_input_tibble` has ", num_obs_ml_input_tibble, " observations of ",
      getNumFeat(ml_input_tibble), " features."
    )
  }

  # Get Resistant/Susceptible proportions.
  if (!multi_class) {
    rs_props_original_ml_input_tibble <- ml_input_tibble |>
      dplyr::count(genome_drug.resistant_phenotype) |>
      dplyr::mutate(prop = n / sum(n))

    if (verbose) {
      rs_props_summary <- paste(
        utils::capture.output(rs_props_original_ml_input_tibble),
        collapse = "\n"
      )
      message(rs_props_summary)
    }

    res_prop_original_ml_input_tibble <- rs_props_original_ml_input_tibble |>
      dplyr::filter(genome_drug.resistant_phenotype == "Resistant") |>
      dplyr::select(prop) |>
      as.numeric() |>
      round(2)

    if (is.na(res_prop_original_ml_input_tibble)) {
      res_prop_original_ml_input_tibble <- 0
    }
  }

  if (shuffle_labels) {
    ml_input_tibble <- shuffleLabels(ml_input_tibble)
  }

  # If external `test_data` is provided...
  if (tibble::is_tibble(test_data)) {
    .checkArgTibble(test_data)

    external_test_data <- TRUE

    if (multi_class) {
      stop(
        "Multi-class classification cannot be performed with ",
        "external test data with the current implementation."
      )
    }

    num_obs_test_data <- nrow(test_data)

    if (verbose) {
      message(
        "`test_data` has ", num_obs_test_data,
        " observations of ", getNumFeat(test_data), " features."
      )
    }

    rs_props_test_data <- test_data |>
      dplyr::count(genome_drug.resistant_phenotype) |>
      dplyr::mutate(prop = n / sum(n))

    if (verbose) {
      test_data_props_summary <- paste(
        utils::capture.output(rs_props_test_data),
        collapse = "\n"
      )
      message(test_data_props_summary)
    }

    # Get the proportion of resistant genomes in the external `test_data`.
    res_prop_test_data <- rs_props_test_data |>
      dplyr::filter(genome_drug.resistant_phenotype == "Resistant") |>
      dplyr::select(prop) |>
      as.numeric() |>
      round(2)

    # Account for the case where no resistance labels are available in the
    # external `test_data`
    if (is.na(res_prop_test_data)) {
      res_prop_test_data <- 0
    }

    # Bind rows as part of the process for making the train/test split if
    # external `test_data` is provided. Remove columns with `NA` values (i.e.,
    # take the union of features across the two tibbles).
    original_ml_input_tibble <- ml_input_tibble
    ml_input_tibble <- dplyr::bind_rows(ml_input_tibble, test_data) |>
      dplyr::select(where(~ !any(is.na(.))))
  }

  data_split <- splitMLInputTibble(ml_input_tibble, split = split)

  # Now correct `data_split` if external `test_data` is provided.
  if (external_test_data & split[2] != 0) {
    # Scale `split` so that it sums to 1 because the entirety of
    # `original_ml_input_tibble` will be used for training and validation.
    scaled_split <- split / sum(split)

    # Get the sizes of the train and validation sets
    n_train <- round(scaled_split[1] * nrow(original_ml_input_tibble))
    n_val <- round(scaled_split[2] * nrow(original_ml_input_tibble))

    # We need to stratify manually by R/S phenotype in the train data. Get
    # relevant measures.
    n_train_res <- round(n_train * res_prop_original_ml_input_tibble)
    res_indices <- which(
      original_ml_input_tibble$genome_drug.resistant_phenotype == "Resistant"
    )

    # Stratify by R/S phenotype
    res_train_indices <- sample(res_indices, n_train_res)
    sus_train_indices <- seq_len(n_train)[!(seq_len(n_train) %in% res_indices)]
    train_indices <- c(res_train_indices, sus_train_indices)

    val_indices <- seq_len(nrow(original_ml_input_tibble))[!(seq_len(nrow(
      original_ml_input_tibble
    )) %in% train_indices)]

    data_split[[2]] <- as.integer(train_indices)
    data_split[[3]] <- as.integer(val_indices)
  } else if (external_test_data & split[2] == 0) { # If using cross-validation...
    n_train <- nrow(original_ml_input_tibble)
    n_val <- 0

    data_split[[2]] <- seq_len(nrow(original_ml_input_tibble))
    data_split[[3]] <- NA
    data_split[[4]] <- tibble::tibble(id = "Resample1")
  }

  train_data <- rsample::training(data_split)
  test_data <- rsample::testing(data_split)

  if (model == "LR") {
    mod <- buildLRModel(multi_class = multi_class)
    grid <- buildTuningGrid(
      model = model, penalty_vec = penalty_vec,
      mix_vec = mix_vec
    )
  }

  recipe <- buildRecipe(train_data,
    use_pca = use_pca,
    pca_threshold = pca_threshold
  )

  wflow <- buildWflow(mod, recipe)

  tune_res <- tuneGrid(
    wflow = wflow, data_split = data_split, grid = grid,
    n_fold = n_fold
  )

  fit <- tune_res |>
    selectBestModel(wflow = wflow, select_best_metric = select_best_metric) |>
    fitBestModel(train_data = train_data)

  if (model == "LR") {
    fit_penalty <- .getFitHps(fit)["penalty"] |> as.numeric()
    fit_mixture <- .getFitHps(fit)["mixture"] |> as.numeric()
  }

  test_data_plus_predictions <- predictML(fit, test_data)

  if (!multi_class) {
    f1 <- .calculateF1(test_data_plus_predictions)
    bal_acc <- .calculateBalAcc(test_data_plus_predictions)
    sens <- .calculateSensitivity(test_data_plus_predictions)
    spec <- .calculateSpecificity(test_data_plus_predictions)
    # From here on out, log2(AUPRC/prior) will be referred to as "log2_apop" for
    # variable naming purposes.
    log2_apop <- .calculateLog2APOP(test_data_plus_predictions)
  }

  mcc <- .calculateMCC(test_data_plus_predictions)
  nmcc <- .calculatenMCC(test_data_plus_predictions)

  if (verbose) {
    message("Matthews correlation coefficient: ", mcc, " | nMCC: ", nmcc)
  }

  top_feat_tibble <- extractTopFeats(fit,
    n_top_feats = n_top_feats,
    prop_vi_top_feats = prop_vi_top_feats
  )

  # Account for the case where a feature was assigned a variable importance of
  # zero, thereby not including the full `n_top_feats` requested. Do this only
  # if `n_top_feats` was specified instead of `prop_vi_top_feats`. Features will
  # be randomly assigned as top hits. This is important for downstream
  # IFE to be able to run.
  if (!multi_class & !is.na(n_top_feats) & nrow(top_feat_tibble) < n_top_feats) {
    all_cols <- colnames(train_data)

    top_feats <- dplyr::pull(top_feat_tibble, Variable)
    importances <- dplyr::pull(top_feat_tibble, Importance)
    signs <- dplyr::pull(top_feat_tibble, Sign)

    # Get a vector of all features that were not assigned a VI score.
    zero_vi_feats <- all_cols[!grepl("genome", all_cols) &
      !(all_cols %in% top_feats)]

    # Get the number of random features that will need to be added to
    # `top_feats`.
    n_random_feats <- n_top_feats - length(top_feats)

    random_indices <- sample(seq_along(zero_vi_feats), n_random_feats)
    random_feats <- zero_vi_feats[random_indices]

    top_feats <- c(top_feats, random_feats)
    importances <- c(importances, rep(0, n_random_feats))
    signs <- c(signs, rep(NA, n_random_feats))

    top_feat_tibble <- tibble::tibble(
      Variable = top_feats,
      Importance = importances, Sign = signs
    )
  }

  if (!multi_class) {
    n_feats_returned <- nrow(top_feat_tibble)
  }

  if (verbose) {
    message("Finished pipeline.")
  }

  end_time <- Sys.time()
  run_time_sec <- round(as.numeric(end_time - start_time, unit = "secs"), 2)

  # Note: if `prop_vi_top_feats` is specified, the function will return the
  # features with variable importance scores between the top
  # `lower_prop_vi_top_feats` and `upper_prop_vi_top_feats` proportions (e.g.,
  # 0 and 0.5, respectively, would indicate that the returned features make up
  # the top 50% of variable importance, or 0.1 and 0.2, respectively, would
  # indicate that the returned features make up the top 10-20% of variable
  # importance).
  performance_tibble <- tibble::tibble(
    num_obs = num_obs_ml_input_tibble,
    n_feat = getNumFeat(ml_input_tibble), model, train_prop = split[1],
    val_prop = split[2], n_fold, mcc, nmcc, run_time_sec, seed,
    date = as.character(Sys.Date())
  )

  if (!multi_class) {
    performance_tibble <- performance_tibble |>
      tibble::add_column(
        res_prop = res_prop_original_ml_input_tibble,
        .after = "num_obs"
      ) |>
      tibble::add_column(n_feats_returned, .before = "n_fold") |>
      tibble::add_column(
        upper_prop_vi_top_feats = prop_vi_top_feats[2],
        .after = "val_prop"
      ) |>
      tibble::add_column(
        lower_prop_vi_top_feats = prop_vi_top_feats[1],
        .after = "val_prop"
      ) |>
      tibble::add_column(bal_acc, .after = "nmcc") |>
      tibble::add_column(f1, .after = "nmcc") |>
      tibble::add_column(log2_apop, .after = "nmcc") |>
      tibble::add_column(sens, .after = "nmcc") |>
      tibble::add_column(spec, .after = "nmcc")
  }

    performance_tibble <- performance_tibble |>
      tibble::add_column(fit_penalty, .before = "mcc") |>
      tibble::add_column(fit_mixture, .before = "mcc")
  

  if (external_test_data) {
    performance_tibble <- performance_tibble |>
      tibble::add_column(num_obs_test_data, .before = "res_prop") |>
      tibble::add_column(res_prop_test_data, .before = "model")

    performance_tibble <- performance_tibble |>
      dplyr::rename(num_obs_original_ml_input_tibble = num_obs) |>
      dplyr::rename(res_prop_original_ml_input_tibble = res_prop) |>
      dplyr::mutate(train_prop = round(n_train / nrow(ml_input_tibble), 2)) |>
      dplyr::mutate(val_prop = round(n_val / nrow(ml_input_tibble), 2))
  }

  all_results <- list(
    performance_tibble = performance_tibble,
    top_feat_tibble = top_feat_tibble
  )

  if (return_tune_res) {
    all_results[["tune_res"]] <- tune_res
  }

  if (return_fit) {
    all_results[["fit"]] <- fit
  }

  if (return_pred) {
    if (!multi_class) {
      all_results[["pred"]] <- test_data_plus_predictions |>
        dplyr::select(c(
          genome_id, .pred_class, .pred_Resistant,
          .pred_Susceptible, genome_drug.resistant_phenotype
        ))
    }
    all_results[["pred"]] <- test_data_plus_predictions
  }

  return(all_results)
}
